# Control Structures

Control Structures are functions in computer programming the evaluate conditions (like, for example, the value of a variable) and change the way code behaves based upon evaluated values. For example, you might to perform one function if the value stored in the variable *x* is greater than 5 and a different function if it is less than less than 5. The [Wikiversit Control Structures page](https://en.wikiversity.org/wiki/Control_structures) contains a good, general description of control structures that is not programming language specific. The information that follows provides examples of the most frequetly used R control structures and how to implement them. For more complete documentation on control strcutures in R run the following help command:

```
?Control
```

## *If* Statement

The "If Statement" is the most basic of the R control structures. It tests whether a particular condition is true. For example, the below statement tests whether the value of the variable *x* is greater than 5. If it is, the code prints the phrase "Yay!" to screen. If it is not, the code does nothing:

```
x <- 7
if (x > 5) {
     print("Yay!")
}
```

Note, the general syntax in the example is:

```
control_statement (condition) {
     #code to execute condition is true
}
```

While you will occasionally see variations in how control structures are present, this is a fairly universal syntax across computer programming languages. The specific control structure being invoked is followed by the *condition* to be tested. Any actions to be performed if the condition evaluates to TRUE are place between curly brackets {} following the condition.

## Relationship Operators

The most common conditions evaluate whether one value is equal to ( *x* == *y*), equal to or greater than (*x* => *y*), equal to or lesser than (*x* <= *y*), greater than (*x* > *y*), or lesser than (*x* < *y*) another value. 

Another common task is to test whether a BOOLEAN value is TRUE or FALSE. The syntax for this evaluation is:

```
if (*x*) { #do something}
```

Control structures in R also have a negation symbol which allows you to specify a negative condition. For example, the conditional statement in the following code evaluates to TRUE (meaning any code placed between the curly brackets will be executed) if the x IS NOT EQUAL to 5:

```
if (x !=5) { #do something}
```

## *If Else* Statement

The "If Else" statement is similar to the "If Statement," but it allows you specify one code path to execute if the conditional evaluates to TRUE and another to execute if the conditional evaluates to FALSE:

```
x <- 7
if (x > 5) {
     print("Yay!")
} else {
     print("Boo!")
}
```

## *ifelse* Statement

R also offers a combined if/else syntax for quick execution of small code chunks:

```
x <- 12
ifelse(x <= 10, "x less than 10", "x greater than 10")
```

## The *switch* Statement

The *switch* statement provides a mechanism for selecting between multiple possible conditions. For example, the following code returns one of several possible values from a list based upon the value of a variable:

```
x <- 3
switch(x,"red","green","blue")
```
*Note: if you pass switch a value that exceeds the number of elements in the list R will not compute a reply.*

## The *which* Statement

The *which* statement is not a true conditional statement, but it provides a very useful way to test the values of a dataset and tell you which elements match a particular condition. In the example below, we load the R IRIS dataset and find out which rows have a Petal.Length greater than 1.4:

```
data("iris")
rows <- which(iris$Petal.Length > 1.4)
```
*note:  you can see all of the R. build in datasets with the data() command.*
