# Common code to run before knitting each chapter.

url <- "./img/mac_finder_1.png"
url2 <- "./img/mac_window_2.png"
url3 <- "./img/spoke_and_where_cloud.png"
url4 <- "./img/distributed_network.png"
url5 <- "./img/hybrid_network.png"
url6 <- "./img/empty_sectors.png"
url7 <- "./img/filled_bits.png"
url8 <- "./img/directory.png"
url9 <- "./img/mac_finder_3.png"
url10 <- "./img/version_tree.png"
url11 <- "./img/TT_tree_mobile.jpg"
url12 <- "./img/mac_terminal.png"
url13 <- "./img/bash.png"
url14 <- "./img/GIT-Branchand-its-Operations.png"
url15 <- "./img/datalab-logo-full-color-rgb.png"
url16 <- "./img/save_stage_commit.png"
url17 <- "./img/git_for_teams.png"
url18 <- "./img/branching_workflows.png"
url19 <- "./img/terminal.png"
url20 <- "./img/terminal_machine_identifier.png"
url21 <- "./img/terminal_file_path.png"
url22 <- "./img/terminal_user.png"
url23 <- "./img/terminal_command_prompt.png"
url24 <- "./img/terminal_cursor_position.png"
url25 <- "./img/terminal_echo_command.png"
url26 <- "./img/terminal_echo_outptu.png"
url27 <- "./img/vim_open.png"
url28 <- "./img/vim_insert_mode.png"
url29 <- "./img/vim_save.png"
url30 <- "https://www.r-project.org/Rlogo.png"
url31 <- "./img/sample_lec7.png"
url32 <- "./img/graph_time_dist_mydata.png"

library(knitr)
