[R]: https://www.r-project.org/
[RStudio]: https://posit.co/products/open-source/rstudio/
[r-download]: https://cloud.r-project.org/
[rstudio-download]: https://posit.co/download/rstudio-desktop/
[git-download]: https://git-scm.com/downloads
[git-install-workshop]: https://ucdavisdatalab.github.io/workshop_introduction_to_version_control/installing-git.html

# Required Software

This course uses free, open source software (OSS). You need to download this software to your computer in order to follow-along with the lessons and complete the associated assignments.

## git

[Git][] is version control system. It helps keep track of changes and updates to your files. You can use it locally on your machine and also on servers.

You can download git for free [here][git-download].

::: {.callout-important}
Windows users require an extra configuration step to include the Git Bash components.

Mac users do not need any extra configuration. We recommend installing it through Xcode.

For more detailed instructions on how to downlad git for your specific operating system see [section 3. Installing Git][git-intall-workshop] from DataLab's Introduction to Version Control workshop.
:::


## R & R Studio

[R][] is a software program for working with data that is excellent for performing statistical analyses and generating data visualizations. [RStudio][] is an integrated deveopment environment [IDE] that provides a user friendly interface for working with R. RStudio will not work if you do not also have R installed. 

You can download R for free [here][r-download].

You can download the RStudio Desktop Open-Source Edition for free
[here][rstudio-download].
