# Required Software {.unnumbered}

This course uses free, open source software. You need to download this software
to your computer in order to follow along with the lessons and complete the
associated assignments.


## Git

[Git][] is version control system. It helps keep track of changes and updates
to your files. You can use it locally on your machine and also on servers.

You can download Git for free [here][git-download].

::: {.callout-note}
On Windows, you can install Git (and Git Bash) with the official installer
linked above.

On macOS, you can install Git automatically together with the Xcode software
development kit by opening the Terminal app, typing `git --version`, and
pressing `Enter` or `Return`.

On Linux, you can install Git with your distribution's package manager.
:::

[Git]: https://git-scm.com/
[git-download]: https://git-scm.com/downloads


## R & R Studio

[R][] is a programming language for working with data, performing statistical
analyses, and generating data visualizations.

You can download R for free [here][r-download].

[RStudio][] is an integrated development environment (IDE) that provides a
user-friendly interface for working with R. RStudio will not work if you do not
also have R installed.

You can download the RStudio Desktop Open-Source Edition for free
[here][rstudio-download].

On Windows, you'll also need to download and install [RTools][] in order for
some of the packages we'll use later to work.

[R]: https://www.r-project.org/
[RStudio]: https://posit.co/products/open-source/rstudio/
[r-download]: https://cloud.r-project.org/
[rstudio-download]: https://posit.co/download/rstudio-desktop/
[RTools]: https://cran.r-project.org/bin/windows/Rtools/
