# Required Software {.unnumbered}

This course uses free, open source software. You need to download this software
to your computer in order to follow along with the lessons and complete the
associated assignments.


## Git

[Git][] is version control system. It helps keep track of changes and updates
to your files. You can use it locally on your machine and also on servers.

You can download Git for free [here][git-download].

::: {.callout-important}
On Windows, an extra configuration step is necessary to make sure Git Bash is
installed with Git.

On macOS, no extra configuration steps are necessary. We recommend installing
Git via Xcode.

For more detailed instructions on how to download Git for your specific
operating system, see the [Installing Git][git-install-workshop] section of
DataLab's Introduction to Version Control workshop.
:::

[Git]: https://git-scm.com/
[git-download]: https://git-scm.com/downloads
[git-install-workshop]: https://ucdavisdatalab.github.io/workshop_introduction_to_version_control/installing-git.html


## R & R Studio

[R][] is a programming language for working with data, performing statistical
analyses, and generating data visualizations.

You can download R for free [here][r-download].

[RStudio][] is an integrated development environment (IDE) that provides a
user-friendly interface for working with R. RStudio will not work if you do not
also have R installed.

You can download the RStudio Desktop Open-Source Edition for free
[here][rstudio-download].

[R]: https://www.r-project.org/
[RStudio]: https://posit.co/products/open-source/rstudio/
[r-download]: https://cloud.r-project.org/
[rstudio-download]: https://posit.co/download/rstudio-desktop/
