<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>20 Statistics | Adventures in Data Science</title>
  <meta name="description" content="20 Statistics | Adventures in Data Science" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="20 Statistics | Adventures in Data Science" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://ucdavisdatalab.github.io/adventures_in_data_science/" />
  
  
  <meta name="github-repo" content="ucdavisdatalab/adventures_in_data_science" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="20 Statistics | Adventures in Data Science" />
  
  
  

<meta name="author" content="Dr. Carl Stahmer" />
<meta name="author" content="Dr. Pamela L. Reynolds" />
<meta name="author" content="Dr. Nick Ulle" />
<meta name="author" content="Dr. Tyler Shoemaker" />
<meta name="author" content="Dr. Michele Tobias" />
<meta name="author" content="Dr. Wesley Brooks" />
<meta name="author" content="Arthur Koehl" />
<meta name="author" content="Carrie Alexander" />
<meta name="author" content="Jared Joseph" />
<meta name="author" content="Liza Wood" />


<meta name="date" content="2022-03-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="network-analysis.html"/>
<link rel="next" href="reshaping-tabular-data.html"/>
<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="libs/str_view-0.1.0/str_view.css" rel="stylesheet" />
<script src="libs/str_view-binding-1.4.0/str_view.js"></script>
<link href="libs/vis-4.20.1/vis.css" rel="stylesheet" />
<script src="libs/vis-4.20.1/vis.min.js"></script>
<script src="libs/visNetwork-binding-2.0.9/visNetwork.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://datalab.ucdavis.edu/">
  <img src="img/datalab-logo-full-color-rgb.png" style="height: 100%; width: 100%; object-fit: contain" />
</a></li>
<li><a href="./" style="font-size: 18px">Adventures in Data Science</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="1" data-path="working-with-the-command-line.html"><a href="working-with-the-command-line.html"><i class="fa fa-check"></i><b>1</b> Working with the Command Line</a>
<ul>
<li class="chapter" data-level="1.1" data-path="working-with-the-command-line.html"><a href="working-with-the-command-line.html#interacting-with-the-command-line"><i class="fa fa-check"></i><b>1.1</b> Interacting with the Command Line</a></li>
<li class="chapter" data-level="1.2" data-path="working-with-the-command-line.html"><a href="working-with-the-command-line.html#common-command-line-commands"><i class="fa fa-check"></i><b>1.2</b> Common Command Line Commands</a></li>
<li class="chapter" data-level="1.3" data-path="working-with-the-command-line.html"><a href="working-with-the-command-line.html#command-line-text-editors"><i class="fa fa-check"></i><b>1.3</b> Command Line Text Editors</a></li>
<li class="chapter" data-level="1.4" data-path="working-with-the-command-line.html"><a href="working-with-the-command-line.html#basic-vim-commands"><i class="fa fa-check"></i><b>1.4</b> Basic Vim Commands</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction-to-version-control.html"><a href="introduction-to-version-control.html"><i class="fa fa-check"></i><b>2</b> Introduction to Version Control</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introduction-to-version-control.html"><a href="introduction-to-version-control.html#what-is-version-control"><i class="fa fa-check"></i><b>2.1</b> What is Version Control?</a></li>
<li class="chapter" data-level="2.2" data-path="introduction-to-version-control.html"><a href="introduction-to-version-control.html#software-assisted-version-control"><i class="fa fa-check"></i><b>2.2</b> Software Assisted Version Control</a></li>
<li class="chapter" data-level="2.3" data-path="introduction-to-version-control.html"><a href="introduction-to-version-control.html#local-vs-server-based-version-control"><i class="fa fa-check"></i><b>2.3</b> Local vs Server Based Version Control</a></li>
<li class="chapter" data-level="2.4" data-path="introduction-to-version-control.html"><a href="introduction-to-version-control.html#central-version-control-systems"><i class="fa fa-check"></i><b>2.4</b> Central Version Control Systems</a></li>
<li class="chapter" data-level="2.5" data-path="introduction-to-version-control.html"><a href="introduction-to-version-control.html#distributed-version-control-systems"><i class="fa fa-check"></i><b>2.5</b> Distributed Version Control Systems</a></li>
<li class="chapter" data-level="2.6" data-path="introduction-to-version-control.html"><a href="introduction-to-version-control.html#the-best-of-both-worlds"><i class="fa fa-check"></i><b>2.6</b> The Best of Both Worlds</a></li>
<li class="chapter" data-level="2.7" data-path="introduction-to-version-control.html"><a href="introduction-to-version-control.html#vcs-and-the-computer-file-system"><i class="fa fa-check"></i><b>2.7</b> VCS and the Computer File System</a></li>
<li class="chapter" data-level="2.8" data-path="introduction-to-version-control.html"><a href="introduction-to-version-control.html#how-computers-store-and-access-information"><i class="fa fa-check"></i><b>2.8</b> How Computers Store and Access Information</a></li>
<li class="chapter" data-level="2.9" data-path="introduction-to-version-control.html"><a href="introduction-to-version-control.html#how-vcs-manage-your-files"><i class="fa fa-check"></i><b>2.9</b> How VCS Manage Your Files</a></li>
<li class="chapter" data-level="2.10" data-path="introduction-to-version-control.html"><a href="introduction-to-version-control.html#graph-based-data-management"><i class="fa fa-check"></i><b>2.10</b> Graph-Based Data Management</a></li>
<li class="chapter" data-level="2.11" data-path="introduction-to-version-control.html"><a href="introduction-to-version-control.html#additional-resources"><i class="fa fa-check"></i><b>2.11</b> Additional Resources</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="git-version-control-basics.html"><a href="git-version-control-basics.html"><i class="fa fa-check"></i><b>3</b> Git Version Control Basics</a>
<ul>
<li class="chapter" data-level="3.1" data-path="git-version-control-basics.html"><a href="git-version-control-basics.html#save-stage-commit"><i class="fa fa-check"></i><b>3.1</b> Save, Stage, Commit</a></li>
<li class="chapter" data-level="3.2" data-path="git-version-control-basics.html"><a href="git-version-control-basics.html#creating-your-first-repo"><i class="fa fa-check"></i><b>3.2</b> Creating Your First Repo</a></li>
<li class="chapter" data-level="3.3" data-path="git-version-control-basics.html"><a href="git-version-control-basics.html#checking-the-status-of-a-repo"><i class="fa fa-check"></i><b>3.3</b> Checking the Status of a Repo</a></li>
<li class="chapter" data-level="3.4" data-path="git-version-control-basics.html"><a href="git-version-control-basics.html#version-of-a-file"><i class="fa fa-check"></i><b>3.4</b> Version of a File</a></li>
<li class="chapter" data-level="3.5" data-path="git-version-control-basics.html"><a href="git-version-control-basics.html#view-a-history-of-your-commits"><i class="fa fa-check"></i><b>3.5</b> View a History of Your Commits</a></li>
<li class="chapter" data-level="3.6" data-path="git-version-control-basics.html"><a href="git-version-control-basics.html#comparing-commits"><i class="fa fa-check"></i><b>3.6</b> Comparing Commits</a></li>
<li class="chapter" data-level="3.7" data-path="git-version-control-basics.html"><a href="git-version-control-basics.html#comparing-files"><i class="fa fa-check"></i><b>3.7</b> Comparing Files</a></li>
<li class="chapter" data-level="3.8" data-path="git-version-control-basics.html"><a href="git-version-control-basics.html#to-view-an-earlier-commit"><i class="fa fa-check"></i><b>3.8</b> To View an Earlier Commit</a></li>
<li class="chapter" data-level="3.9" data-path="git-version-control-basics.html"><a href="git-version-control-basics.html#undoing-things"><i class="fa fa-check"></i><b>3.9</b> Undoing Things</a></li>
<li class="chapter" data-level="3.10" data-path="git-version-control-basics.html"><a href="git-version-control-basics.html#when-things-go-wrong"><i class="fa fa-check"></i><b>3.10</b> When Things go Wrong!</a></li>
<li class="chapter" data-level="3.11" data-path="git-version-control-basics.html"><a href="git-version-control-basics.html#git-branching"><i class="fa fa-check"></i><b>3.11</b> Git Branching</a>
<ul>
<li class="chapter" data-level="3.11.1" data-path="git-version-control-basics.html"><a href="git-version-control-basics.html#merging-branches"><i class="fa fa-check"></i><b>3.11.1</b> Merging Branches</a></li>
<li class="chapter" data-level="3.11.2" data-path="git-version-control-basics.html"><a href="git-version-control-basics.html#branching-workflows"><i class="fa fa-check"></i><b>3.11.2</b> Branching Workflows</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="working-with-remote-repositories.html"><a href="working-with-remote-repositories.html"><i class="fa fa-check"></i><b>4</b> Working with Remote Repositories</a>
<ul>
<li class="chapter" data-level="4.1" data-path="working-with-remote-repositories.html"><a href="working-with-remote-repositories.html#github-basics"><i class="fa fa-check"></i><b>4.1</b> GitHub Basics</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="working-with-remote-repositories.html"><a href="working-with-remote-repositories.html#communicating-through-github"><i class="fa fa-check"></i><b>4.1.1</b> Communicating Through GitHub</a></li>
<li class="chapter" data-level="4.1.2" data-path="working-with-remote-repositories.html"><a href="working-with-remote-repositories.html#what-should-i-push-to-github"><i class="fa fa-check"></i><b>4.1.2</b> What Should I Push to GitHub?</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="working-with-remote-repositories.html"><a href="working-with-remote-repositories.html#basic-github-account-setup"><i class="fa fa-check"></i><b>4.2</b> Basic GitHub Account Setup</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="working-with-remote-repositories.html"><a href="working-with-remote-repositories.html#locally-setting-up-your-git-credentials"><i class="fa fa-check"></i><b>4.2.1</b> Locally Setting Up Your Git Credentials</a></li>
<li class="chapter" data-level="4.2.2" data-path="working-with-remote-repositories.html"><a href="working-with-remote-repositories.html#ssh-keys-and-github"><i class="fa fa-check"></i><b>4.2.2</b> SSH Keys and GitHub</a></li>
<li class="chapter" data-level="4.2.3" data-path="working-with-remote-repositories.html"><a href="working-with-remote-repositories.html#connecting-to-github-with-ssh"><i class="fa fa-check"></i><b>4.2.3</b> Connecting to GitHub with SSH</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="working-with-remote-repositories.html"><a href="working-with-remote-repositories.html#github-desktop-or-the-command-line"><i class="fa fa-check"></i><b>4.3</b> GitHub Desktop, or the Command Line?</a></li>
<li class="chapter" data-level="4.4" data-path="working-with-remote-repositories.html"><a href="working-with-remote-repositories.html#sync-with-github"><i class="fa fa-check"></i><b>4.4</b> Sync with GitHub</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="working-with-remote-repositories.html"><a href="working-with-remote-repositories.html#preparing-to-sync-your-repository"><i class="fa fa-check"></i><b>4.4.1</b> Preparing to Sync Your Repository</a></li>
<li class="chapter" data-level="4.4.2" data-path="working-with-remote-repositories.html"><a href="working-with-remote-repositories.html#pushing-a-local-repository"><i class="fa fa-check"></i><b>4.4.2</b> Pushing a Local Repository</a></li>
<li class="chapter" data-level="4.4.3" data-path="working-with-remote-repositories.html"><a href="working-with-remote-repositories.html#tracking-files-remotely"><i class="fa fa-check"></i><b>4.4.3</b> Tracking Files Remotely</a></li>
<li class="chapter" data-level="4.4.4" data-path="working-with-remote-repositories.html"><a href="working-with-remote-repositories.html#pulling-changes-from-a-remote-repository"><i class="fa fa-check"></i><b>4.4.4</b> Pulling Changes from a Remote Repository</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="working-with-remote-repositories.html"><a href="working-with-remote-repositories.html#cloning-a-repository"><i class="fa fa-check"></i><b>4.5</b> Cloning a Repository</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="working-with-remote-repositories.html"><a href="working-with-remote-repositories.html#how-to-clone-a-repository"><i class="fa fa-check"></i><b>4.5.1</b> How to Clone a Repository</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>5</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="5.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#learning-objectives"><i class="fa fa-check"></i><b>5.1</b> Learning objectives</a></li>
<li class="chapter" data-level="5.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#before-we-start"><i class="fa fa-check"></i><b>5.2</b> Before We Start</a></li>
<li class="chapter" data-level="5.3" data-path="introduction-to-r.html"><a href="introduction-to-r.html#mathematical-operations"><i class="fa fa-check"></i><b>5.3</b> Mathematical Operations</a></li>
<li class="chapter" data-level="5.4" data-path="introduction-to-r.html"><a href="introduction-to-r.html#variables"><i class="fa fa-check"></i><b>5.4</b> Variables</a></li>
<li class="chapter" data-level="5.5" data-path="introduction-to-r.html"><a href="introduction-to-r.html#calling-functions"><i class="fa fa-check"></i><b>5.5</b> Calling Functions</a></li>
<li class="chapter" data-level="5.6" data-path="introduction-to-r.html"><a href="introduction-to-r.html#help"><i class="fa fa-check"></i><b>5.6</b> HELP!</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#when-something-goes-wrong-and-it-will"><i class="fa fa-check"></i><b>5.6.1</b> When Something Goes Wrong (and it will)</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="introduction-to-r.html"><a href="introduction-to-r.html#vectors"><i class="fa fa-check"></i><b>5.7</b> Vectors</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#indexing-vectors"><i class="fa fa-check"></i><b>5.7.1</b> Indexing Vectors</a></li>
<li class="chapter" data-level="5.7.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#vectorization"><i class="fa fa-check"></i><b>5.7.2</b> Vectorization</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="introduction-to-r.html"><a href="introduction-to-r.html#data-frames"><i class="fa fa-check"></i><b>5.8</b> Data Frames</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#selecting-columns"><i class="fa fa-check"></i><b>5.8.1</b> Selecting Columns</a></li>
<li class="chapter" data-level="5.8.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#inspecting-data"><i class="fa fa-check"></i><b>5.8.2</b> Inspecting Data</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="introduction-to-r.html"><a href="introduction-to-r.html#data-types-classes"><i class="fa fa-check"></i><b>5.9</b> Data Types &amp; Classes</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#lists"><i class="fa fa-check"></i><b>5.9.1</b> Lists</a></li>
<li class="chapter" data-level="5.9.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#implicit-coercion"><i class="fa fa-check"></i><b>5.9.2</b> Implicit Coercion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="control-structures.html"><a href="control-structures.html"><i class="fa fa-check"></i><b>6</b> Control Structures</a>
<ul>
<li class="chapter" data-level="6.1" data-path="control-structures.html"><a href="control-structures.html#if-statement"><i class="fa fa-check"></i><b>6.1</b> <em>If</em> Statement</a></li>
<li class="chapter" data-level="6.2" data-path="control-structures.html"><a href="control-structures.html#relationship-operators"><i class="fa fa-check"></i><b>6.2</b> Relationship Operators</a></li>
<li class="chapter" data-level="6.3" data-path="control-structures.html"><a href="control-structures.html#if-else-statement"><i class="fa fa-check"></i><b>6.3</b> <em>If Else</em> Statement</a></li>
<li class="chapter" data-level="6.4" data-path="control-structures.html"><a href="control-structures.html#ifelse-statement"><i class="fa fa-check"></i><b>6.4</b> <em>ifelse</em> Statement</a></li>
<li class="chapter" data-level="6.5" data-path="control-structures.html"><a href="control-structures.html#the-switch-statement"><i class="fa fa-check"></i><b>6.5</b> The <em>switch</em> Statement</a></li>
<li class="chapter" data-level="6.6" data-path="control-structures.html"><a href="control-structures.html#the-which-statement"><i class="fa fa-check"></i><b>6.6</b> The <em>which</em> Statement</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="iterating-loops.html"><a href="iterating-loops.html"><i class="fa fa-check"></i><b>7</b> Iterating (Loops)</a>
<ul>
<li class="chapter" data-level="7.1" data-path="iterating-loops.html"><a href="iterating-loops.html#for-i-in-x-loops"><i class="fa fa-check"></i><b>7.1</b> For <em>i</em> in <em>x</em> Loops</a></li>
<li class="chapter" data-level="7.2" data-path="iterating-loops.html"><a href="iterating-loops.html#while-loops"><i class="fa fa-check"></i><b>7.2</b> <em>While</em> Loops</a></li>
<li class="chapter" data-level="7.3" data-path="iterating-loops.html"><a href="iterating-loops.html#repeat-loops"><i class="fa fa-check"></i><b>7.3</b> <em>Repeat</em> Loops</a></li>
<li class="chapter" data-level="7.4" data-path="iterating-loops.html"><a href="iterating-loops.html#break-and-next"><i class="fa fa-check"></i><b>7.4</b> <em>Break</em> and <em>Next</em></a></li>
<li class="chapter" data-level="7.5" data-path="iterating-loops.html"><a href="iterating-loops.html#iterating-data.frame-rows-in-r"><i class="fa fa-check"></i><b>7.5</b> Iterating Data.Frame Rows in R</a></li>
<li class="chapter" data-level="7.6" data-path="iterating-loops.html"><a href="iterating-loops.html#lapply"><i class="fa fa-check"></i><b>7.6</b> <em>lapply()</em></a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>8</b> Functions</a>
<ul>
<li class="chapter" data-level="8.1" data-path="functions.html"><a href="functions.html#learning-objectives-1"><i class="fa fa-check"></i><b>8.1</b> Learning objectives</a></li>
<li class="chapter" data-level="8.2" data-path="functions.html"><a href="functions.html#what-is-a-function"><i class="fa fa-check"></i><b>8.2</b> What is a function?</a></li>
<li class="chapter" data-level="8.3" data-path="functions.html"><a href="functions.html#what-is-the-basic-syntax-of-a-function-in-r"><i class="fa fa-check"></i><b>8.3</b> What is the basic syntax of a function in R?</a></li>
<li class="chapter" data-level="8.4" data-path="functions.html"><a href="functions.html#building-and-calling-functions"><i class="fa fa-check"></i><b>8.4</b> Building and calling functions</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="functions.html"><a href="functions.html#step-1-building-the-function"><i class="fa fa-check"></i><b>8.4.1</b> Step 1: Building the function</a></li>
<li class="chapter" data-level="8.4.2" data-path="functions.html"><a href="functions.html#step-2-calling-the-function"><i class="fa fa-check"></i><b>8.4.2</b> Step 2: Calling the function</a></li>
<li class="chapter" data-level="8.4.3" data-path="functions.html"><a href="functions.html#example-function-with-one-argument"><i class="fa fa-check"></i><b>8.4.3</b> Example function with one argument</a></li>
<li class="chapter" data-level="8.4.4" data-path="functions.html"><a href="functions.html#example-function-with-more-than-one-argument"><i class="fa fa-check"></i><b>8.4.4</b> Example function with more than one argument</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="functions.html"><a href="functions.html#saving-functions-and-sourcing-them-from-another-file"><i class="fa fa-check"></i><b>8.5</b> Saving functions and sourcing them from another file</a></li>
<li class="chapter" data-level="8.6" data-path="functions.html"><a href="functions.html#saving-functions-and-calling-them-from-another-file"><i class="fa fa-check"></i><b>8.6</b> Saving functions and calling them from another file</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="working-with-files-and-packages.html"><a href="working-with-files-and-packages.html"><i class="fa fa-check"></i><b>9</b> Working with Files and Packages</a>
<ul>
<li class="chapter" data-level="9.1" data-path="working-with-files-and-packages.html"><a href="working-with-files-and-packages.html#learning-objectives-2"><i class="fa fa-check"></i><b>9.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="9.2" data-path="working-with-files-and-packages.html"><a href="working-with-files-and-packages.html#setup"><i class="fa fa-check"></i><b>9.2</b> Setup</a></li>
<li class="chapter" data-level="9.3" data-path="working-with-files-and-packages.html"><a href="working-with-files-and-packages.html#exploring-files"><i class="fa fa-check"></i><b>9.3</b> Exploring Files</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="working-with-files-and-packages.html"><a href="working-with-files-and-packages.html#file-extensions"><i class="fa fa-check"></i><b>9.3.1</b> File Extensions</a></li>
<li class="chapter" data-level="9.3.2" data-path="working-with-files-and-packages.html"><a href="working-with-files-and-packages.html#text-files"><i class="fa fa-check"></i><b>9.3.2</b> Text Files</a></li>
<li class="chapter" data-level="9.3.3" data-path="working-with-files-and-packages.html"><a href="working-with-files-and-packages.html#binary-files"><i class="fa fa-check"></i><b>9.3.3</b> Binary Files</a></li>
<li class="chapter" data-level="9.3.4" data-path="working-with-files-and-packages.html"><a href="working-with-files-and-packages.html#common-data-file-types"><i class="fa fa-check"></i><b>9.3.4</b> Common Data File Types</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="working-with-files-and-packages.html"><a href="working-with-files-and-packages.html#reading-and-writing-files-in-r"><i class="fa fa-check"></i><b>9.4</b> Reading and Writing Files in R</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="working-with-files-and-packages.html"><a href="working-with-files-and-packages.html#the-working-directory"><i class="fa fa-check"></i><b>9.4.1</b> The Working Directory</a></li>
<li class="chapter" data-level="9.4.2" data-path="working-with-files-and-packages.html"><a href="working-with-files-and-packages.html#reading-a-csv-file"><i class="fa fa-check"></i><b>9.4.2</b> Reading a CSV File</a></li>
<li class="chapter" data-level="9.4.3" data-path="working-with-files-and-packages.html"><a href="working-with-files-and-packages.html#reader-functions-for-tabular-data"><i class="fa fa-check"></i><b>9.4.3</b> Reader Functions for Tabular Data</a></li>
<li class="chapter" data-level="9.4.4" data-path="working-with-files-and-packages.html"><a href="working-with-files-and-packages.html#rds"><i class="fa fa-check"></i><b>9.4.4</b> RDS</a></li>
<li class="chapter" data-level="9.4.5" data-path="working-with-files-and-packages.html"><a href="working-with-files-and-packages.html#writing-a-csv"><i class="fa fa-check"></i><b>9.4.5</b> Writing a csv</a></li>
<li class="chapter" data-level="9.4.6" data-path="working-with-files-and-packages.html"><a href="working-with-files-and-packages.html#excel-files-in-r"><i class="fa fa-check"></i><b>9.4.6</b> Excel Files in R</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="working-with-files-and-packages.html"><a href="working-with-files-and-packages.html#packages"><i class="fa fa-check"></i><b>9.5</b> Packages</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="working-with-files-and-packages.html"><a href="working-with-files-and-packages.html#cran"><i class="fa fa-check"></i><b>9.5.1</b> CRAN</a></li>
<li class="chapter" data-level="9.5.2" data-path="working-with-files-and-packages.html"><a href="working-with-files-and-packages.html#using-packages"><i class="fa fa-check"></i><b>9.5.2</b> Using Packages</a></li>
<li class="chapter" data-level="9.5.3" data-path="working-with-files-and-packages.html"><a href="working-with-files-and-packages.html#load-excel-data"><i class="fa fa-check"></i><b>9.5.3</b> Load Excel Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="factors-special-values-and-indexing.html"><a href="factors-special-values-and-indexing.html"><i class="fa fa-check"></i><b>10</b> Factors, Special Values, and Indexing</a>
<ul>
<li class="chapter" data-level="10.1" data-path="factors-special-values-and-indexing.html"><a href="factors-special-values-and-indexing.html#learning-objectives-3"><i class="fa fa-check"></i><b>10.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="10.2" data-path="factors-special-values-and-indexing.html"><a href="factors-special-values-and-indexing.html#factors"><i class="fa fa-check"></i><b>10.2</b> Factors</a></li>
<li class="chapter" data-level="10.3" data-path="factors-special-values-and-indexing.html"><a href="factors-special-values-and-indexing.html#special-values"><i class="fa fa-check"></i><b>10.3</b> Special Values</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="factors-special-values-and-indexing.html"><a href="factors-special-values-and-indexing.html#missing-values"><i class="fa fa-check"></i><b>10.3.1</b> Missing Values</a></li>
<li class="chapter" data-level="10.3.2" data-path="factors-special-values-and-indexing.html"><a href="factors-special-values-and-indexing.html#not-a-number"><i class="fa fa-check"></i><b>10.3.2</b> Not a Number</a></li>
<li class="chapter" data-level="10.3.3" data-path="factors-special-values-and-indexing.html"><a href="factors-special-values-and-indexing.html#null"><i class="fa fa-check"></i><b>10.3.3</b> Null</a></li>
<li class="chapter" data-level="10.3.4" data-path="factors-special-values-and-indexing.html"><a href="factors-special-values-and-indexing.html#infinity"><i class="fa fa-check"></i><b>10.3.4</b> Infinity</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="factors-special-values-and-indexing.html"><a href="factors-special-values-and-indexing.html#indexing"><i class="fa fa-check"></i><b>10.4</b> Indexing</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="factors-special-values-and-indexing.html"><a href="factors-special-values-and-indexing.html#all-elements"><i class="fa fa-check"></i><b>10.4.1</b> All Elements</a></li>
<li class="chapter" data-level="10.4.2" data-path="factors-special-values-and-indexing.html"><a href="factors-special-values-and-indexing.html#by-position"><i class="fa fa-check"></i><b>10.4.2</b> By Position</a></li>
<li class="chapter" data-level="10.4.3" data-path="factors-special-values-and-indexing.html"><a href="factors-special-values-and-indexing.html#by-name"><i class="fa fa-check"></i><b>10.4.3</b> By Name</a></li>
<li class="chapter" data-level="10.4.4" data-path="factors-special-values-and-indexing.html"><a href="factors-special-values-and-indexing.html#by-condition"><i class="fa fa-check"></i><b>10.4.4</b> By Condition</a></li>
<li class="chapter" data-level="10.4.5" data-path="factors-special-values-and-indexing.html"><a href="factors-special-values-and-indexing.html#logic"><i class="fa fa-check"></i><b>10.4.5</b> Logic</a></li>
<li class="chapter" data-level="10.4.6" data-path="factors-special-values-and-indexing.html"><a href="factors-special-values-and-indexing.html#indexing-lists"><i class="fa fa-check"></i><b>10.4.6</b> Indexing Lists</a></li>
<li class="chapter" data-level="10.4.7" data-path="factors-special-values-and-indexing.html"><a href="factors-special-values-and-indexing.html#indexing-data-frames"><i class="fa fa-check"></i><b>10.4.7</b> Indexing Data Frames</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="data-forensics.html"><a href="data-forensics.html"><i class="fa fa-check"></i><b>11</b> Data Forensics</a>
<ul>
<li class="chapter" data-level="11.1" data-path="data-forensics.html"><a href="data-forensics.html#learning-objectives-4"><i class="fa fa-check"></i><b>11.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="11.2" data-path="data-forensics.html"><a href="data-forensics.html#structural-summaries-cleaning"><i class="fa fa-check"></i><b>11.2</b> Structural Summaries &amp; Cleaning</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="data-forensics.html"><a href="data-forensics.html#dates"><i class="fa fa-check"></i><b>11.2.1</b> Dates</a></li>
<li class="chapter" data-level="11.2.2" data-path="data-forensics.html"><a href="data-forensics.html#tidy-data"><i class="fa fa-check"></i><b>11.2.2</b> Tidy Data</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="data-forensics.html"><a href="data-forensics.html#statistical-forensics"><i class="fa fa-check"></i><b>11.3</b> Statistical Forensics</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="data-forensics.html"><a href="data-forensics.html#missing-values-1"><i class="fa fa-check"></i><b>11.3.1</b> Missing Values</a></li>
<li class="chapter" data-level="11.3.2" data-path="data-forensics.html"><a href="data-forensics.html#outliers"><i class="fa fa-check"></i><b>11.3.2</b> Outliers</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="data-forensics.html"><a href="data-forensics.html#apply-functions"><i class="fa fa-check"></i><b>11.4</b> Apply Functions</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="data-forensics.html"><a href="data-forensics.html#the-sapply-function"><i class="fa fa-check"></i><b>11.4.1</b> The <code>sapply</code> Function</a></li>
<li class="chapter" data-level="11.4.2" data-path="data-forensics.html"><a href="data-forensics.html#the-split-apply-pattern"><i class="fa fa-check"></i><b>11.4.2</b> The Split-Apply Pattern</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="data-structures.html"><a href="data-structures.html"><i class="fa fa-check"></i><b>12</b> Data Structures</a>
<ul>
<li class="chapter" data-level="12.1" data-path="data-structures.html"><a href="data-structures.html#tabular-data"><i class="fa fa-check"></i><b>12.1</b> Tabular Data</a></li>
<li class="chapter" data-level="12.2" data-path="data-structures.html"><a href="data-structures.html#tree-document-data-structures"><i class="fa fa-check"></i><b>12.2</b> Tree / Document Data Structures</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="data-structures.html"><a href="data-structures.html#structuring-data-as-xml"><i class="fa fa-check"></i><b>12.2.1</b> Structuring Data as XML</a></li>
<li class="chapter" data-level="12.2.2" data-path="data-structures.html"><a href="data-structures.html#structuring-data-as-json"><i class="fa fa-check"></i><b>12.2.2</b> Structuring Data as JSON</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="data-structures.html"><a href="data-structures.html#relational-databases"><i class="fa fa-check"></i><b>12.3</b> Relational Databases</a></li>
<li class="chapter" data-level="12.4" data-path="data-structures.html"><a href="data-structures.html#non-hierarchical-relational-data"><i class="fa fa-check"></i><b>12.4</b> Non-Hierarchical Relational Data</a></li>
<li class="chapter" data-level="12.5" data-path="data-structures.html"><a href="data-structures.html#geospatial-data"><i class="fa fa-check"></i><b>12.5</b> Geospatial Data</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html"><i class="fa fa-check"></i><b>13</b> Data Visualization Principles &amp; Perception</a>
<ul>
<li class="chapter" data-level="13.1" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#learning-objectives-5"><i class="fa fa-check"></i><b>13.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="13.2" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#introduction"><i class="fa fa-check"></i><b>13.2</b> Introduction</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#a-brief-history-of-data-visualization"><i class="fa fa-check"></i><b>13.2.1</b> A Brief History of Data Visualization</a></li>
<li class="chapter" data-level="13.2.2" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#famous-data-visualizations"><i class="fa fa-check"></i><b>13.2.2</b> Famous Data Visualizations</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#what-is-data-visualization"><i class="fa fa-check"></i><b>13.3</b> What is Data Visualization?</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#why-viz"><i class="fa fa-check"></i><b>13.3.1</b> Why viz?</a></li>
<li class="chapter" data-level="13.3.2" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#good-data-visualizations"><i class="fa fa-check"></i><b>13.3.2</b> Good data visualizations</a></li>
<li class="chapter" data-level="13.3.3" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#bad-data-visualizations"><i class="fa fa-check"></i><b>13.3.3</b> Bad data visualizations</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#before-you-viz-make-a-plan"><i class="fa fa-check"></i><b>13.4</b> Before You Viz, Make a Plan</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#purpose"><i class="fa fa-check"></i><b>13.4.1</b> Purpose</a></li>
<li class="chapter" data-level="13.4.2" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#audience"><i class="fa fa-check"></i><b>13.4.2</b> Audience</a></li>
<li class="chapter" data-level="13.4.3" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#medium"><i class="fa fa-check"></i><b>13.4.3</b> Medium</a></li>
<li class="chapter" data-level="13.4.4" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#tools"><i class="fa fa-check"></i><b>13.4.4</b> Tools</a></li>
<li class="chapter" data-level="13.4.5" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#message"><i class="fa fa-check"></i><b>13.4.5</b> Message</a></li>
<li class="chapter" data-level="13.4.6" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#critical-approaches"><i class="fa fa-check"></i><b>13.4.6</b> Critical Approaches</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#graphical-elements-of-a-plot"><i class="fa fa-check"></i><b>13.5</b> Graphical Elements of a Plot</a></li>
<li class="chapter" data-level="13.6" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#principles-of-visual-perception"><i class="fa fa-check"></i><b>13.6</b> Principles of Visual Perception</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#visual-magic-tricks"><i class="fa fa-check"></i><b>13.6.1</b> Visual Magic Tricks</a></li>
<li class="chapter" data-level="13.6.2" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#stevens-psychophysical-power-law"><i class="fa fa-check"></i><b>13.6.2</b> Steven’s Psychophysical Power Law</a></li>
<li class="chapter" data-level="13.6.3" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#perception-and-encodings"><i class="fa fa-check"></i><b>13.6.3</b> Perception and Encodings</a></li>
<li class="chapter" data-level="13.6.4" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#evaluating-graphics"><i class="fa fa-check"></i><b>13.6.4</b> Evaluating Graphics</a></li>
<li class="chapter" data-level="13.6.5" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#gestalt-principles"><i class="fa fa-check"></i><b>13.6.5</b> Gestalt Principles</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#accessible-data-visualizations"><i class="fa fa-check"></i><b>13.7</b> Accessible Data Visualizations</a></li>
<li class="chapter" data-level="13.8" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#designing-statistical-graphics"><i class="fa fa-check"></i><b>13.8</b> Designing Statistical Graphics</a>
<ul>
<li class="chapter" data-level="13.8.1" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#step-1-identify-your-data-type"><i class="fa fa-check"></i><b>13.8.1</b> Step 1: Identify Your Data Type</a></li>
<li class="chapter" data-level="13.8.2" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#step-2-determine-your-functional-approach"><i class="fa fa-check"></i><b>13.8.2</b> Step 2: Determine Your Functional Approach</a></li>
<li class="chapter" data-level="13.8.3" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#step-3-select-a-plot-type"><i class="fa fa-check"></i><b>13.8.3</b> Step 3: Select a Plot Type</a></li>
<li class="chapter" data-level="13.8.4" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#step-4-iterate"><i class="fa fa-check"></i><b>13.8.4</b> Step 4: Iterate</a></li>
</ul></li>
<li class="chapter" data-level="13.9" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#tips-for-better-plots"><i class="fa fa-check"></i><b>13.9</b> Tips for Better Plots</a>
<ul>
<li class="chapter" data-level="13.9.1" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#get-rid-of-chartjunk"><i class="fa fa-check"></i><b>13.9.1</b> Get Rid of Chartjunk</a></li>
<li class="chapter" data-level="13.9.2" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#facilitate-comparisons"><i class="fa fa-check"></i><b>13.9.2</b> Facilitate Comparisons</a></li>
<li class="chapter" data-level="13.9.3" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#create-information-rich-plots"><i class="fa fa-check"></i><b>13.9.3</b> Create Information-Rich Plots</a></li>
<li class="chapter" data-level="13.9.4" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#dont-distort-the-data"><i class="fa fa-check"></i><b>13.9.4</b> Don’t Distort the Data</a></li>
<li class="chapter" data-level="13.9.5" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#practice"><i class="fa fa-check"></i><b>13.9.5</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="13.10" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#references-and-additional-resources"><i class="fa fa-check"></i><b>13.10</b> References and Additional Resources</a>
<ul>
<li class="chapter" data-level="13.10.1" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#articles"><i class="fa fa-check"></i><b>13.10.1</b> Articles</a></li>
<li class="chapter" data-level="13.10.2" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#websites"><i class="fa fa-check"></i><b>13.10.2</b> Websites</a></li>
<li class="chapter" data-level="13.10.3" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#books-and-chapters"><i class="fa fa-check"></i><b>13.10.3</b> Books and Chapters</a></li>
<li class="chapter" data-level="13.10.4" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#historical-books"><i class="fa fa-check"></i><b>13.10.4</b> Historical Books</a></li>
<li class="chapter" data-level="13.10.5" data-path="data-visualization-principles-perception.html"><a href="data-visualization-principles-perception.html#r-graphics-references"><i class="fa fa-check"></i><b>13.10.5</b> R Graphics References</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="data-viz-with-ggplot-in-r.html"><a href="data-viz-with-ggplot-in-r.html"><i class="fa fa-check"></i><b>14</b> Data Viz with ggplot in R</a>
<ul>
<li class="chapter" data-level="14.1" data-path="data-viz-with-ggplot-in-r.html"><a href="data-viz-with-ggplot-in-r.html#learning-objectives-6"><i class="fa fa-check"></i><b>14.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="14.2" data-path="data-viz-with-ggplot-in-r.html"><a href="data-viz-with-ggplot-in-r.html#r-graphics-overview"><i class="fa fa-check"></i><b>14.2</b> R Graphics Overview</a></li>
<li class="chapter" data-level="14.3" data-path="data-viz-with-ggplot-in-r.html"><a href="data-viz-with-ggplot-in-r.html#the-grammar-of-graphics"><i class="fa fa-check"></i><b>14.3</b> The Grammar of Graphics</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="data-viz-with-ggplot-in-r.html"><a href="data-viz-with-ggplot-in-r.html#making-a-plot"><i class="fa fa-check"></i><b>14.3.1</b> Making a Plot</a></li>
<li class="chapter" data-level="14.3.2" data-path="data-viz-with-ggplot-in-r.html"><a href="data-viz-with-ggplot-in-r.html#saving-plots"><i class="fa fa-check"></i><b>14.3.2</b> Saving Plots</a></li>
<li class="chapter" data-level="14.3.3" data-path="data-viz-with-ggplot-in-r.html"><a href="data-viz-with-ggplot-in-r.html#example-bar-plot"><i class="fa fa-check"></i><b>14.3.3</b> Example: Bar Plot</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="data-viz-with-ggplot-in-r.html"><a href="data-viz-with-ggplot-in-r.html#remembering-factors"><i class="fa fa-check"></i><b>14.4</b> Remembering factors</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="data-viz-with-ggplot-in-r.html"><a href="data-viz-with-ggplot-in-r.html#assigning-factor-levels"><i class="fa fa-check"></i><b>14.4.1</b> Assigning factor levels</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="data-viz-with-ggplot-in-r.html"><a href="data-viz-with-ggplot-in-r.html#designing-a-visualization"><i class="fa fa-check"></i><b>14.5</b> Designing a Visualization</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="how-the-web-works.html"><a href="how-the-web-works.html"><i class="fa fa-check"></i><b>15</b> How the Web Works</a>
<ul>
<li class="chapter" data-level="15.1" data-path="how-the-web-works.html"><a href="how-the-web-works.html#client-server-architecture"><i class="fa fa-check"></i><b>15.1</b> Client-Server Architecture</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="how-the-web-works.html"><a href="how-the-web-works.html#communication-between-clients-and-servers"><i class="fa fa-check"></i><b>15.1.1</b> Communication Between Clients and Servers</a></li>
<li class="chapter" data-level="15.1.2" data-path="how-the-web-works.html"><a href="how-the-web-works.html#domain-name-resolution"><i class="fa fa-check"></i><b>15.1.2</b> Domain Name Resolution</a></li>
<li class="chapter" data-level="15.1.3" data-path="how-the-web-works.html"><a href="how-the-web-works.html#request-routing"><i class="fa fa-check"></i><b>15.1.3</b> Request Routing</a></li>
<li class="chapter" data-level="15.1.4" data-path="how-the-web-works.html"><a href="how-the-web-works.html#the-server-response"><i class="fa fa-check"></i><b>15.1.4</b> The Server Response</a></li>
<li class="chapter" data-level="15.1.5" data-path="how-the-web-works.html"><a href="how-the-web-works.html#internet-transfer-protocols"><i class="fa fa-check"></i><b>15.1.5</b> Internet Transfer Protocols</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="how-the-web-works.html"><a href="how-the-web-works.html#understanding-urls"><i class="fa fa-check"></i><b>15.2</b> Understanding URLs</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="how-the-web-works.html"><a href="how-the-web-works.html#dynamic-files"><i class="fa fa-check"></i><b>15.2.1</b> Dynamic Files</a></li>
<li class="chapter" data-level="15.2.2" data-path="how-the-web-works.html"><a href="how-the-web-works.html#query-strings"><i class="fa fa-check"></i><b>15.2.2</b> Query Strings</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="getting-data-from-the-web.html"><a href="getting-data-from-the-web.html"><i class="fa fa-check"></i><b>16</b> Getting Data from the Web</a>
<ul>
<li class="chapter" data-level="16.1" data-path="getting-data-from-the-web.html"><a href="getting-data-from-the-web.html#overview-1"><i class="fa fa-check"></i><b>16.1</b> Overview</a></li>
<li class="chapter" data-level="16.2" data-path="getting-data-from-the-web.html"><a href="getting-data-from-the-web.html#apis"><i class="fa fa-check"></i><b>16.2</b> APIs</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="getting-data-from-the-web.html"><a href="getting-data-from-the-web.html#querying-to-an-api"><i class="fa fa-check"></i><b>16.2.1</b> Querying to an API</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="getting-data-from-the-web.html"><a href="getting-data-from-the-web.html#web-scraping"><i class="fa fa-check"></i><b>16.3</b> Web Scraping</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="getting-data-from-the-web.html"><a href="getting-data-from-the-web.html#whats-in-a-web-page"><i class="fa fa-check"></i><b>16.3.1</b> What’s in a Web Page?</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="getting-data-from-the-web.html"><a href="getting-data-from-the-web.html#rs-xml-parsers"><i class="fa fa-check"></i><b>16.4</b> R’s XML Parsers</a></li>
<li class="chapter" data-level="16.5" data-path="getting-data-from-the-web.html"><a href="getting-data-from-the-web.html#xpath"><i class="fa fa-check"></i><b>16.5</b> XPath</a>
<ul>
<li class="chapter" data-level="16.5.1" data-path="getting-data-from-the-web.html"><a href="getting-data-from-the-web.html#predicates"><i class="fa fa-check"></i><b>16.5.1</b> Predicates</a></li>
</ul></li>
<li class="chapter" data-level="16.6" data-path="getting-data-from-the-web.html"><a href="getting-data-from-the-web.html#the-web-scraping-workflow"><i class="fa fa-check"></i><b>16.6</b> The Web Scraping Workflow</a>
<ul>
<li class="chapter" data-level="16.6.1" data-path="getting-data-from-the-web.html"><a href="getting-data-from-the-web.html#being-polite"><i class="fa fa-check"></i><b>16.6.1</b> Being Polite</a></li>
</ul></li>
<li class="chapter" data-level="16.7" data-path="getting-data-from-the-web.html"><a href="getting-data-from-the-web.html#case-study-ca-cities"><i class="fa fa-check"></i><b>16.7</b> Case Study: CA Cities</a>
<ul>
<li class="chapter" data-level="16.7.1" data-path="getting-data-from-the-web.html"><a href="getting-data-from-the-web.html#data-cleaning"><i class="fa fa-check"></i><b>16.7.1</b> Data Cleaning</a></li>
</ul></li>
<li class="chapter" data-level="16.8" data-path="getting-data-from-the-web.html"><a href="getting-data-from-the-web.html#case-study-the-ca-aggie"><i class="fa fa-check"></i><b>16.8</b> Case Study: The CA Aggie</a></li>
<li class="chapter" data-level="16.9" data-path="getting-data-from-the-web.html"><a href="getting-data-from-the-web.html#css-selectors"><i class="fa fa-check"></i><b>16.9</b> CSS Selectors</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="strings-and-regular-expressions.html"><a href="strings-and-regular-expressions.html"><i class="fa fa-check"></i><b>17</b> Strings and Regular Expressions</a>
<ul>
<li class="chapter" data-level="17.1" data-path="strings-and-regular-expressions.html"><a href="strings-and-regular-expressions.html#printing-output"><i class="fa fa-check"></i><b>17.1</b> Printing Output</a></li>
<li class="chapter" data-level="17.2" data-path="strings-and-regular-expressions.html"><a href="strings-and-regular-expressions.html#escape-sequences"><i class="fa fa-check"></i><b>17.2</b> Escape Sequences</a>
<ul>
<li class="chapter" data-level="17.2.1" data-path="strings-and-regular-expressions.html"><a href="strings-and-regular-expressions.html#raw-strings"><i class="fa fa-check"></i><b>17.2.1</b> Raw Strings</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="strings-and-regular-expressions.html"><a href="strings-and-regular-expressions.html#character-encodings"><i class="fa fa-check"></i><b>17.3</b> Character Encodings</a></li>
<li class="chapter" data-level="17.4" data-path="strings-and-regular-expressions.html"><a href="strings-and-regular-expressions.html#the-tidyverse"><i class="fa fa-check"></i><b>17.4</b> The Tidyverse</a></li>
<li class="chapter" data-level="17.5" data-path="strings-and-regular-expressions.html"><a href="strings-and-regular-expressions.html#the-stringr-package"><i class="fa fa-check"></i><b>17.5</b> The stringr Package</a>
<ul>
<li class="chapter" data-level="17.5.1" data-path="strings-and-regular-expressions.html"><a href="strings-and-regular-expressions.html#splitting-strings"><i class="fa fa-check"></i><b>17.5.1</b> Splitting Strings</a></li>
<li class="chapter" data-level="17.5.2" data-path="strings-and-regular-expressions.html"><a href="strings-and-regular-expressions.html#replacing-parts-of-strings"><i class="fa fa-check"></i><b>17.5.2</b> Replacing Parts of Strings</a></li>
</ul></li>
<li class="chapter" data-level="17.6" data-path="strings-and-regular-expressions.html"><a href="strings-and-regular-expressions.html#regular-expressions"><i class="fa fa-check"></i><b>17.6</b> Regular Expressions</a>
<ul>
<li class="chapter" data-level="17.6.1" data-path="strings-and-regular-expressions.html"><a href="strings-and-regular-expressions.html#the-wildcard"><i class="fa fa-check"></i><b>17.6.1</b> The Wildcard</a></li>
<li class="chapter" data-level="17.6.2" data-path="strings-and-regular-expressions.html"><a href="strings-and-regular-expressions.html#escape-sequences-1"><i class="fa fa-check"></i><b>17.6.2</b> Escape Sequences</a></li>
<li class="chapter" data-level="17.6.3" data-path="strings-and-regular-expressions.html"><a href="strings-and-regular-expressions.html#anchors"><i class="fa fa-check"></i><b>17.6.3</b> Anchors</a></li>
<li class="chapter" data-level="17.6.4" data-path="strings-and-regular-expressions.html"><a href="strings-and-regular-expressions.html#character-classes"><i class="fa fa-check"></i><b>17.6.4</b> Character Classes</a></li>
<li class="chapter" data-level="17.6.5" data-path="strings-and-regular-expressions.html"><a href="strings-and-regular-expressions.html#quantifiers"><i class="fa fa-check"></i><b>17.6.5</b> Quantifiers</a></li>
<li class="chapter" data-level="17.6.6" data-path="strings-and-regular-expressions.html"><a href="strings-and-regular-expressions.html#groups"><i class="fa fa-check"></i><b>17.6.6</b> Groups</a></li>
<li class="chapter" data-level="17.6.7" data-path="strings-and-regular-expressions.html"><a href="strings-and-regular-expressions.html#extracting-matches"><i class="fa fa-check"></i><b>17.6.7</b> Extracting Matches</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="optical-character-recognition.html"><a href="optical-character-recognition.html"><i class="fa fa-check"></i><b>18</b> Optical Character Recognition</a>
<ul>
<li class="chapter" data-level="18.1" data-path="optical-character-recognition.html"><a href="optical-character-recognition.html#loading-page-images"><i class="fa fa-check"></i><b>18.1</b> Loading Page Images</a></li>
<li class="chapter" data-level="18.2" data-path="optical-character-recognition.html"><a href="optical-character-recognition.html#running-ocr"><i class="fa fa-check"></i><b>18.2</b> Running OCR</a></li>
<li class="chapter" data-level="18.3" data-path="optical-character-recognition.html"><a href="optical-character-recognition.html#accuracy"><i class="fa fa-check"></i><b>18.3</b> Accuracy</a></li>
<li class="chapter" data-level="18.4" data-path="optical-character-recognition.html"><a href="optical-character-recognition.html#unreadable-text"><i class="fa fa-check"></i><b>18.4</b> Unreadable Text</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="network-analysis.html"><a href="network-analysis.html"><i class="fa fa-check"></i><b>19</b> Network Analysis</a>
<ul>
<li class="chapter" data-level="19.1" data-path="network-analysis.html"><a href="network-analysis.html#overview-2"><i class="fa fa-check"></i><b>19.1</b> Overview</a>
<ul>
<li class="chapter" data-level="19.1.1" data-path="network-analysis.html"><a href="network-analysis.html#while-you-wait"><i class="fa fa-check"></i><b>19.1.1</b> While you wait</a></li>
<li class="chapter" data-level="19.1.2" data-path="network-analysis.html"><a href="network-analysis.html#learning-objectives-7"><i class="fa fa-check"></i><b>19.1.2</b> Learning Objectives</a></li>
<li class="chapter" data-level="19.1.3" data-path="network-analysis.html"><a href="network-analysis.html#roadmap"><i class="fa fa-check"></i><b>19.1.3</b> Roadmap</a></li>
</ul></li>
<li class="chapter" data-level="19.2" data-path="network-analysis.html"><a href="network-analysis.html#what-is-network-analysis"><i class="fa fa-check"></i><b>19.2</b> What is Network Analysis</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="network-analysis.html"><a href="network-analysis.html#networks-in-research---social-sciences"><i class="fa fa-check"></i><b>19.2.1</b> Networks in research - Social Sciences</a></li>
<li class="chapter" data-level="19.2.2" data-path="network-analysis.html"><a href="network-analysis.html#networks-in-research---neuroscience"><i class="fa fa-check"></i><b>19.2.2</b> Networks in research - Neuroscience</a></li>
<li class="chapter" data-level="19.2.3" data-path="network-analysis.html"><a href="network-analysis.html#networks-in-research---chemistry"><i class="fa fa-check"></i><b>19.2.3</b> Networks in research - Chemistry</a></li>
<li class="chapter" data-level="19.2.4" data-path="network-analysis.html"><a href="network-analysis.html#networks-in-research---the-internet"><i class="fa fa-check"></i><b>19.2.4</b> Networks in research - The Internet</a></li>
<li class="chapter" data-level="19.2.5" data-path="network-analysis.html"><a href="network-analysis.html#networks-in-research---infrastructure"><i class="fa fa-check"></i><b>19.2.5</b> Networks in research - Infrastructure</a></li>
<li class="chapter" data-level="19.2.6" data-path="network-analysis.html"><a href="network-analysis.html#networks-in-research---security"><i class="fa fa-check"></i><b>19.2.6</b> Networks in research - Security</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="network-analysis.html"><a href="network-analysis.html#network-data"><i class="fa fa-check"></i><b>19.3</b> Network Data</a>
<ul>
<li class="chapter" data-level="19.3.1" data-path="network-analysis.html"><a href="network-analysis.html#edgelist"><i class="fa fa-check"></i><b>19.3.1</b> Edgelist</a></li>
<li class="chapter" data-level="19.3.2" data-path="network-analysis.html"><a href="network-analysis.html#adjacency-matrix"><i class="fa fa-check"></i><b>19.3.2</b> Adjacency Matrix</a></li>
<li class="chapter" data-level="19.3.3" data-path="network-analysis.html"><a href="network-analysis.html#edge-weights"><i class="fa fa-check"></i><b>19.3.3</b> Edge Weights</a></li>
<li class="chapter" data-level="19.3.4" data-path="network-analysis.html"><a href="network-analysis.html#attributes"><i class="fa fa-check"></i><b>19.3.4</b> Attributes</a></li>
<li class="chapter" data-level="19.3.5" data-path="network-analysis.html"><a href="network-analysis.html#create-an-example-network"><i class="fa fa-check"></i><b>19.3.5</b> Create an Example Network</a></li>
<li class="chapter" data-level="19.3.6" data-path="network-analysis.html"><a href="network-analysis.html#components"><i class="fa fa-check"></i><b>19.3.6</b> Components</a></li>
<li class="chapter" data-level="19.3.7" data-path="network-analysis.html"><a href="network-analysis.html#limitations-of-network-data"><i class="fa fa-check"></i><b>19.3.7</b> Limitations of Network Data</a></li>
<li class="chapter" data-level="19.3.8" data-path="network-analysis.html"><a href="network-analysis.html#projected-networks"><i class="fa fa-check"></i><b>19.3.8</b> Projected Networks</a></li>
</ul></li>
<li class="chapter" data-level="19.4" data-path="network-analysis.html"><a href="network-analysis.html#graph-level-properties"><i class="fa fa-check"></i><b>19.4</b> Graph Level Properties</a>
<ul>
<li class="chapter" data-level="19.4.1" data-path="network-analysis.html"><a href="network-analysis.html#directed-or-un-directed"><i class="fa fa-check"></i><b>19.4.1</b> Directed or Un-directed</a></li>
<li class="chapter" data-level="19.4.2" data-path="network-analysis.html"><a href="network-analysis.html#density"><i class="fa fa-check"></i><b>19.4.2</b> Density</a></li>
<li class="chapter" data-level="19.4.3" data-path="network-analysis.html"><a href="network-analysis.html#centralization"><i class="fa fa-check"></i><b>19.4.3</b> Centralization</a></li>
</ul></li>
<li class="chapter" data-level="19.5" data-path="network-analysis.html"><a href="network-analysis.html#node-level-properties"><i class="fa fa-check"></i><b>19.5</b> Node Level Properties</a>
<ul>
<li class="chapter" data-level="19.5.1" data-path="network-analysis.html"><a href="network-analysis.html#degree"><i class="fa fa-check"></i><b>19.5.1</b> Degree</a></li>
<li class="chapter" data-level="19.5.2" data-path="network-analysis.html"><a href="network-analysis.html#geodesic-distance"><i class="fa fa-check"></i><b>19.5.2</b> Geodesic Distance</a></li>
<li class="chapter" data-level="19.5.3" data-path="network-analysis.html"><a href="network-analysis.html#centrality"><i class="fa fa-check"></i><b>19.5.3</b> Centrality</a></li>
</ul></li>
<li class="chapter" data-level="19.6" data-path="network-analysis.html"><a href="network-analysis.html#network-workflow"><i class="fa fa-check"></i><b>19.6</b> Network Workflow</a></li>
<li class="chapter" data-level="19.7" data-path="network-analysis.html"><a href="network-analysis.html#network-tools"><i class="fa fa-check"></i><b>19.7</b> Network Tools</a>
<ul>
<li class="chapter" data-level="19.7.1" data-path="network-analysis.html"><a href="network-analysis.html#network-models"><i class="fa fa-check"></i><b>19.7.1</b> Network Models</a></li>
<li class="chapter" data-level="19.7.2" data-path="network-analysis.html"><a href="network-analysis.html#network-visualization"><i class="fa fa-check"></i><b>19.7.2</b> Network Visualization</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="statistics.html"><a href="statistics.html"><i class="fa fa-check"></i><b>20</b> Statistics</a>
<ul>
<li class="chapter" data-level="20.1" data-path="statistics.html"><a href="statistics.html#introduction-1"><i class="fa fa-check"></i><b>20.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="20.1.1" data-path="statistics.html"><a href="statistics.html#mice_pot-dataset"><i class="fa fa-check"></i><b>20.1.1</b> <code>mice_pot</code> dataset</a></li>
<li class="chapter" data-level="20.1.2" data-path="statistics.html"><a href="statistics.html#barnacles-dataset"><i class="fa fa-check"></i><b>20.1.2</b> <code>barnacles</code> dataset</a></li>
<li class="chapter" data-level="20.1.3" data-path="statistics.html"><a href="statistics.html#sample-and-population"><i class="fa fa-check"></i><b>20.1.3</b> Sample and population</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="statistics.html"><a href="statistics.html#uses-of-simulation"><i class="fa fa-check"></i><b>20.2</b> Uses of simulation</a></li>
<li class="chapter" data-level="20.3" data-path="statistics.html"><a href="statistics.html#mathematical-statistics"><i class="fa fa-check"></i><b>20.3</b> Mathematical statistics</a>
<ul>
<li class="chapter" data-level="20.3.1" data-path="statistics.html"><a href="statistics.html#law-of-large-numbers"><i class="fa fa-check"></i><b>20.3.1</b> Law of large numbers</a></li>
<li class="chapter" data-level="20.3.2" data-path="statistics.html"><a href="statistics.html#central-limit-theorem"><i class="fa fa-check"></i><b>20.3.2</b> Central limit theorem</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="statistics.html"><a href="statistics.html#statistical-inference"><i class="fa fa-check"></i><b>20.4</b> Statistical inference</a>
<ul>
<li class="chapter" data-level="20.4.1" data-path="statistics.html"><a href="statistics.html#confidence-intervals"><i class="fa fa-check"></i><b>20.4.1</b> Confidence intervals</a></li>
<li class="chapter" data-level="20.4.2" data-path="statistics.html"><a href="statistics.html#two-population-test"><i class="fa fa-check"></i><b>20.4.2</b> Two-population test</a></li>
<li class="chapter" data-level="20.4.3" data-path="statistics.html"><a href="statistics.html#hypothesis-tests-for-non-normal-data"><i class="fa fa-check"></i><b>20.4.3</b> Hypothesis tests for non-normal data</a></li>
</ul></li>
<li class="chapter" data-level="20.5" data-path="statistics.html"><a href="statistics.html#regression"><i class="fa fa-check"></i><b>20.5</b> Regression</a>
<ul>
<li class="chapter" data-level="20.5.1" data-path="statistics.html"><a href="statistics.html#fitting-a-regression-line"><i class="fa fa-check"></i><b>20.5.1</b> Fitting a regression line</a></li>
<li class="chapter" data-level="20.5.2" data-path="statistics.html"><a href="statistics.html#assumptions-and-diagnostics"><i class="fa fa-check"></i><b>20.5.2</b> Assumptions and diagnostics</a></li>
<li class="chapter" data-level="20.5.3" data-path="statistics.html"><a href="statistics.html#functions-for-inspecting-regression-fits"><i class="fa fa-check"></i><b>20.5.3</b> Functions for inspecting regression fits</a></li>
<li class="chapter" data-level="20.5.4" data-path="statistics.html"><a href="statistics.html#a-model-that-fails-diagnostics"><i class="fa fa-check"></i><b>20.5.4</b> A model that fails diagnostics</a></li>
<li class="chapter" data-level="20.5.5" data-path="statistics.html"><a href="statistics.html#predictions-and-variability"><i class="fa fa-check"></i><b>20.5.5</b> Predictions and variability</a></li>
</ul></li>
<li class="chapter" data-level="20.6" data-path="statistics.html"><a href="statistics.html#model-selection"><i class="fa fa-check"></i><b>20.6</b> Model selection</a></li>
<li class="chapter" data-level="20.7" data-path="statistics.html"><a href="statistics.html#cross-validation"><i class="fa fa-check"></i><b>20.7</b> Cross-validation</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="reshaping-tabular-data.html"><a href="reshaping-tabular-data.html"><i class="fa fa-check"></i><b>21</b> Reshaping Tabular Data</a>
<ul>
<li class="chapter" data-level="21.1" data-path="reshaping-tabular-data.html"><a href="reshaping-tabular-data.html#learning-objectives-8"><i class="fa fa-check"></i><b>21.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="21.2" data-path="reshaping-tabular-data.html"><a href="reshaping-tabular-data.html#introduction-2"><i class="fa fa-check"></i><b>21.2</b> Introduction</a>
<ul>
<li class="chapter" data-level="21.2.1" data-path="reshaping-tabular-data.html"><a href="reshaping-tabular-data.html#columns-into-rows"><i class="fa fa-check"></i><b>21.2.1</b> Columns into Rows</a></li>
<li class="chapter" data-level="21.2.2" data-path="reshaping-tabular-data.html"><a href="reshaping-tabular-data.html#rows-into-columns"><i class="fa fa-check"></i><b>21.2.2</b> Rows into Columns</a></li>
<li class="chapter" data-level="21.2.3" data-path="reshaping-tabular-data.html"><a href="reshaping-tabular-data.html#separating-values"><i class="fa fa-check"></i><b>21.2.3</b> Separating Values</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="22" data-path="data-forensics-and-cleaning-unstructured-data.html"><a href="data-forensics-and-cleaning-unstructured-data.html"><i class="fa fa-check"></i><b>22</b> Data Forensics and Cleaning: Unstructured Data</a>
<ul>
<li class="chapter" data-level="22.1" data-path="data-forensics-and-cleaning-unstructured-data.html"><a href="data-forensics-and-cleaning-unstructured-data.html#preliminaries"><i class="fa fa-check"></i><b>22.1</b> Preliminaries</a></li>
<li class="chapter" data-level="22.2" data-path="data-forensics-and-cleaning-unstructured-data.html"><a href="data-forensics-and-cleaning-unstructured-data.html#using-a-file-manifest"><i class="fa fa-check"></i><b>22.2</b> Using a File Manifest</a></li>
<li class="chapter" data-level="22.3" data-path="data-forensics-and-cleaning-unstructured-data.html"><a href="data-forensics-and-cleaning-unstructured-data.html#loading-a-corpus"><i class="fa fa-check"></i><b>22.3</b> Loading a Corpus</a></li>
<li class="chapter" data-level="22.4" data-path="data-forensics-and-cleaning-unstructured-data.html"><a href="data-forensics-and-cleaning-unstructured-data.html#preprocessing"><i class="fa fa-check"></i><b>22.4</b> Preprocessing</a>
<ul>
<li class="chapter" data-level="22.4.1" data-path="data-forensics-and-cleaning-unstructured-data.html"><a href="data-forensics-and-cleaning-unstructured-data.html#tokenizing-and-bags-of-words"><i class="fa fa-check"></i><b>22.4.1</b> Tokenizing and Bags of Words</a></li>
<li class="chapter" data-level="22.4.2" data-path="data-forensics-and-cleaning-unstructured-data.html"><a href="data-forensics-and-cleaning-unstructured-data.html#text-normalization"><i class="fa fa-check"></i><b>22.4.2</b> Text Normalization</a></li>
<li class="chapter" data-level="22.4.3" data-path="data-forensics-and-cleaning-unstructured-data.html"><a href="data-forensics-and-cleaning-unstructured-data.html#stop-words"><i class="fa fa-check"></i><b>22.4.3</b> Stop Words</a></li>
<li class="chapter" data-level="22.4.4" data-path="data-forensics-and-cleaning-unstructured-data.html"><a href="data-forensics-and-cleaning-unstructured-data.html#tokenizers"><i class="fa fa-check"></i><b>22.4.4</b> Tokenizers</a></li>
<li class="chapter" data-level="22.4.5" data-path="data-forensics-and-cleaning-unstructured-data.html"><a href="data-forensics-and-cleaning-unstructured-data.html#document-chunking-and-n-grams"><i class="fa fa-check"></i><b>22.4.5</b> Document Chunking and N-grams</a></li>
</ul></li>
<li class="chapter" data-level="22.5" data-path="data-forensics-and-cleaning-unstructured-data.html"><a href="data-forensics-and-cleaning-unstructured-data.html#counting-terms"><i class="fa fa-check"></i><b>22.5</b> Counting Terms</a>
<ul>
<li class="chapter" data-level="22.5.1" data-path="data-forensics-and-cleaning-unstructured-data.html"><a href="data-forensics-and-cleaning-unstructured-data.html#term-frequency"><i class="fa fa-check"></i><b>22.5.1</b> Term Frequency</a></li>
<li class="chapter" data-level="22.5.2" data-path="data-forensics-and-cleaning-unstructured-data.html"><a href="data-forensics-and-cleaning-unstructured-data.html#plotting-term-frequency"><i class="fa fa-check"></i><b>22.5.2</b> Plotting Term Frequency</a></li>
<li class="chapter" data-level="22.5.3" data-path="data-forensics-and-cleaning-unstructured-data.html"><a href="data-forensics-and-cleaning-unstructured-data.html#comparing-term-frequencies-across-documents"><i class="fa fa-check"></i><b>22.5.3</b> Comparing Term Frequencies Across Documents</a></li>
</ul></li>
<li class="chapter" data-level="22.6" data-path="data-forensics-and-cleaning-unstructured-data.html"><a href="data-forensics-and-cleaning-unstructured-data.html#text-mining-pipepline"><i class="fa fa-check"></i><b>22.6</b> Text Mining Pipepline</a></li>
<li class="chapter" data-level="22.7" data-path="data-forensics-and-cleaning-unstructured-data.html"><a href="data-forensics-and-cleaning-unstructured-data.html#document-term-matrix"><i class="fa fa-check"></i><b>22.7</b> Document Term Matrix</a></li>
<li class="chapter" data-level="22.8" data-path="data-forensics-and-cleaning-unstructured-data.html"><a href="data-forensics-and-cleaning-unstructured-data.html#corpus-analytics"><i class="fa fa-check"></i><b>22.8</b> Corpus Analytics</a>
<ul>
<li class="chapter" data-level="22.8.1" data-path="data-forensics-and-cleaning-unstructured-data.html"><a href="data-forensics-and-cleaning-unstructured-data.html#corpus-term-counts"><i class="fa fa-check"></i><b>22.8.1</b> Corpus Term Counts</a></li>
<li class="chapter" data-level="22.8.2" data-path="data-forensics-and-cleaning-unstructured-data.html"><a href="data-forensics-and-cleaning-unstructured-data.html#tfidf-scores"><i class="fa fa-check"></i><b>22.8.2</b> tf–idf Scores</a></li>
<li class="chapter" data-level="22.8.3" data-path="data-forensics-and-cleaning-unstructured-data.html"><a href="data-forensics-and-cleaning-unstructured-data.html#unique-terms-in-a-document"><i class="fa fa-check"></i><b>22.8.3</b> Unique Terms in a Document</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="23" data-path="data-forensics-and-cleaning-geospatial-data.html"><a href="data-forensics-and-cleaning-geospatial-data.html"><i class="fa fa-check"></i><b>23</b> Data Forensics and Cleaning: Geospatial Data</a>
<ul>
<li class="chapter" data-level="23.1" data-path="data-forensics-and-cleaning-geospatial-data.html"><a href="data-forensics-and-cleaning-geospatial-data.html#learning-objectives-9"><i class="fa fa-check"></i><b>23.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="23.2" data-path="data-forensics-and-cleaning-geospatial-data.html"><a href="data-forensics-and-cleaning-geospatial-data.html#what-is-geospatial-data"><i class="fa fa-check"></i><b>23.2</b> What is Geospatial Data?</a>
<ul>
<li class="chapter" data-level="23.2.1" data-path="data-forensics-and-cleaning-geospatial-data.html"><a href="data-forensics-and-cleaning-geospatial-data.html#attributes-1"><i class="fa fa-check"></i><b>23.2.1</b> Attributes</a></li>
<li class="chapter" data-level="23.2.2" data-path="data-forensics-and-cleaning-geospatial-data.html"><a href="data-forensics-and-cleaning-geospatial-data.html#coordinate-reference-system"><i class="fa fa-check"></i><b>23.2.2</b> Coordinate Reference System</a></li>
<li class="chapter" data-level="23.2.3" data-path="data-forensics-and-cleaning-geospatial-data.html"><a href="data-forensics-and-cleaning-geospatial-data.html#coordinates"><i class="fa fa-check"></i><b>23.2.3</b> Coordinates</a></li>
</ul></li>
<li class="chapter" data-level="23.3" data-path="data-forensics-and-cleaning-geospatial-data.html"><a href="data-forensics-and-cleaning-geospatial-data.html#geospatial-data-models"><i class="fa fa-check"></i><b>23.3</b> Geospatial Data Models</a>
<ul>
<li class="chapter" data-level="23.3.1" data-path="data-forensics-and-cleaning-geospatial-data.html"><a href="data-forensics-and-cleaning-geospatial-data.html#vector-data"><i class="fa fa-check"></i><b>23.3.1</b> Vector Data</a></li>
<li class="chapter" data-level="23.3.2" data-path="data-forensics-and-cleaning-geospatial-data.html"><a href="data-forensics-and-cleaning-geospatial-data.html#raster-data"><i class="fa fa-check"></i><b>23.3.2</b> Raster Data</a></li>
</ul></li>
<li class="chapter" data-level="23.4" data-path="data-forensics-and-cleaning-geospatial-data.html"><a href="data-forensics-and-cleaning-geospatial-data.html#data-structures-applied-to-geospatial-data"><i class="fa fa-check"></i><b>23.4</b> Data Structures Applied to Geospatial Data</a></li>
<li class="chapter" data-level="23.5" data-path="data-forensics-and-cleaning-geospatial-data.html"><a href="data-forensics-and-cleaning-geospatial-data.html#cleaning-geospatial-data"><i class="fa fa-check"></i><b>23.5</b> Cleaning Geospatial Data</a>
<ul>
<li class="chapter" data-level="23.5.1" data-path="data-forensics-and-cleaning-geospatial-data.html"><a href="data-forensics-and-cleaning-geospatial-data.html#example-data"><i class="fa fa-check"></i><b>23.5.1</b> Example Data</a></li>
<li class="chapter" data-level="23.5.2" data-path="data-forensics-and-cleaning-geospatial-data.html"><a href="data-forensics-and-cleaning-geospatial-data.html#making-location-data-usable"><i class="fa fa-check"></i><b>23.5.2</b> Making Location Data Usable</a></li>
<li class="chapter" data-level="23.5.3" data-path="data-forensics-and-cleaning-geospatial-data.html"><a href="data-forensics-and-cleaning-geospatial-data.html#cleaning-location-data"><i class="fa fa-check"></i><b>23.5.3</b> Cleaning Location Data</a></li>
<li class="chapter" data-level="23.5.4" data-path="data-forensics-and-cleaning-geospatial-data.html"><a href="data-forensics-and-cleaning-geospatial-data.html#cleaning-attribute-data"><i class="fa fa-check"></i><b>23.5.4</b> Cleaning Attribute Data</a></li>
<li class="chapter" data-level="23.5.5" data-path="data-forensics-and-cleaning-geospatial-data.html"><a href="data-forensics-and-cleaning-geospatial-data.html#checking-coordinate-reference-systems"><i class="fa fa-check"></i><b>23.5.5</b> Checking Coordinate Reference Systems</a></li>
</ul></li>
<li class="chapter" data-level="23.6" data-path="data-forensics-and-cleaning-geospatial-data.html"><a href="data-forensics-and-cleaning-geospatial-data.html#conclusions"><i class="fa fa-check"></i><b>23.6</b> Conclusions</a></li>
<li class="chapter" data-level="23.7" data-path="data-forensics-and-cleaning-geospatial-data.html"><a href="data-forensics-and-cleaning-geospatial-data.html#optional-further-reading"><i class="fa fa-check"></i><b>23.7</b> Optional Further Reading</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>24</b> References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Adventures in Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="statistics" class="section level1" number="20">
<h1><span class="header-section-number">20</span> Statistics</h1>
<div id="introduction-1" class="section level2" number="20.1">
<h2><span class="header-section-number">20.1</span> Introduction</h2>
<p>It is useful to begin with some concrete examples of statistical questions to motivate the material that we’ll cover in the workshop. This will also help confirm that your R environment is working. These data files come from the <code>fosdata</code> package, which you can optionally install to your computer in order to get access to all the associated metadata in the help files. I will show loading the data from the workshop website.</p>
<pre><code># optional: install the fosdata and mosaicModels packages using remotes::install_github
install.packages( &quot;remotes&quot; )
remotes::install_github( &quot;speegled/fosdata&quot; )
remotes::install_github( &quot;ProjectMOSAIC/mosaicModel&quot; )</code></pre>
<div class="sourceCode" id="cb716"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb716-1"><a href="statistics.html#cb716-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>( <span class="st">&quot;ggformula&quot;</span> )</span>
<span id="cb716-2"><a href="statistics.html#cb716-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>( <span class="st">&quot;mosaic&quot;</span> )</span>
<span id="cb716-3"><a href="statistics.html#cb716-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>( <span class="st">&quot;mosaicModel&quot;</span> )</span></code></pre></div>
<div class="sourceCode" id="cb717"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb717-1"><a href="statistics.html#cb717-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the datasets</span></span>
<span id="cb717-2"><a href="statistics.html#cb717-2" aria-hidden="true" tabindex="-1"></a>mice_pot <span class="ot">=</span> <span class="fu">read.csv</span>( <span class="fu">url</span>( <span class="st">&quot;https://raw.githubusercontent.com/ucdavisdatalab/adventures_in_data_science/master/data/mice_pot.csv&quot;</span> ))</span>
<span id="cb717-3"><a href="statistics.html#cb717-3" aria-hidden="true" tabindex="-1"></a>barnacles <span class="ot">=</span> <span class="fu">read.csv</span>( <span class="fu">url</span>( <span class="st">&quot;https://raw.githubusercontent.com/ucdavisdatalab/adventures_in_data_science/master/data/barnacles.csv&quot;</span> ))</span>
<span id="cb717-4"><a href="statistics.html#cb717-4" aria-hidden="true" tabindex="-1"></a>Births78 <span class="ot">=</span> <span class="fu">read.csv</span>( <span class="fu">url</span>(<span class="st">&quot;https://raw.githubusercontent.com/ucdavisdatalab/adventures_in_data_science/master/data/births.csv&quot;</span>))</span>
<span id="cb717-5"><a href="statistics.html#cb717-5" aria-hidden="true" tabindex="-1"></a>smoking <span class="ot">=</span> <span class="fu">read.csv</span>( <span class="fu">url</span>(<span class="st">&quot;https://raw.githubusercontent.com/ucdavisdatalab/adventures_in_data_science/master/data/smoking.csv&quot;</span>))</span>
<span id="cb717-6"><a href="statistics.html#cb717-6" aria-hidden="true" tabindex="-1"></a>adipose <span class="ot">=</span> <span class="fu">read.csv</span>( <span class="fu">url</span>(<span class="st">&quot;https://raw.githubusercontent.com/ucdavisdatalab/adventures_in_data_science/master/data/adipose.csv&quot;</span>))</span></code></pre></div>
<div id="mice_pot-dataset" class="section level3" number="20.1.1">
<h3><span class="header-section-number">20.1.1</span> <code>mice_pot</code> dataset</h3>
<p>The <code>mice_pot</code> dataset contains data on an experiment that dosed four groups of mice with different levels of THC. There was a low, medium, and high dosage group, as well as a control group that got no THC. The mice were were then observed for a while and their total movement was quantified as a percentage of the baseline group mean. Some statistical questions that might arise here are: were there differences in the typical amount of movement between mice of different groups? What was the average amount of movement by mice in the medium dose group?</p>
<p>Both of these questions can be approached in ways that relate to the particular sample, which is kind of interesting descriptions of the data. For instance, if you install the <code>dplyr</code> package in your R environment, we can make those calculations right now.</p>
<div class="sourceCode" id="cb718"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb718-1"><a href="statistics.html#cb718-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>( mice_pot, <span class="fu">by</span>(percent_of_act, group, mean))</span></code></pre></div>
<pre><code>## group: 0.3
## [1] 97.3225
## ------------------------------------------------------------ 
## group: 1
## [1] 99.05235
## ------------------------------------------------------------ 
## group: 3
## [1] 70.66787
## ------------------------------------------------------------ 
## group: VEH
## [1] 100</code></pre>
<p>The means aren’t identical - there are clearly differences between all of the groups? Yes, <strong>in terms of the sample</strong>. But if you want to generalize your conclusion to cover what would happen to other mice that weren’t in the study, then you need to think about the <strong>population</strong>. In this case, that’s the population of all the mice that could have been dosed with THC.</p>
<p>Because we don’t see we don’t see data from mice that weren’t part of the study, we rely on statistical <strong>inference</strong> to reach conclusions about the population. How is that possible? Well, some theorems from <strong>mathematical statistics</strong> can tell us about the <strong>distribution</strong> of the sample, relative to the population</p>
</div>
<div id="barnacles-dataset" class="section level3" number="20.1.2">
<h3><span class="header-section-number">20.1.2</span> <code>barnacles</code> dataset</h3>
<p>This dataset was collected by counting the barnacles in 88 grid squares on the Flower Garden Banks coral reef in the Gulf of Mexico. The counts were normalized to barnacles per square meter. Some questions that you might approach with statistical methods are, what is the average number of barnacles per square meter, and is it greater than 300?</p>
<div class="sourceCode" id="cb720"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb720-1"><a href="statistics.html#cb720-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>( barnacles<span class="sc">$</span>per_m )</span></code></pre></div>
<pre><code>## [1] 332.0186</code></pre>
<p>From that calculation, we see that the mean is 332 barnacles per square meter, which is greater than 300. But again, the first calculation has told us only about the mean of the particular locations that were sampled. Wouldn’t it be better to answer the questions by reference to the number of barnaces per square meter of reef, rather than square meter of measurement? Here, the <strong>population</strong> is then entire area of the Flower Garden Banks reef. Again, we will be able to answer the questions relative to the entire reef by working out the sample mean’s distribution, relative to the population.</p>
</div>
<div id="sample-and-population" class="section level3" number="20.1.3">
<h3><span class="header-section-number">20.1.3</span> Sample and population</h3>
<p>I’ve made reference to samples and populations, and they are fundamental concepts in statistics. A sample is a pretty easy thing to understand - it is the data, the hard numbers that go into your calculations. The population is trickier. It’s the units to which you are able to generalize your conclusions.</p>
<p>For the barnacle data, in order for the population to be the entire Flower Garden Banks reef, the sample must have been carefully selected to ensure it was representative of the entire reef (for instance, randomly sampling locations so that any location on the reef might have been selected).</p>
<p>For the mice on THC, the population is all the mice that might have been selected for use in the experiment. How big that population is depends on how the mice were selected for the experiment. Randomly selecting the experimental units from a group is a common way of ensuring that the results can generalize to that whole group.</p>
<p>A non-random sample tends to mean that the population to which you can generalize is quite limited. What sort of population do you think we could generalize about if we recorded the age of everyone in this class?</p>
</div>
</div>
<div id="uses-of-simulation" class="section level2" number="20.2">
<h2><span class="header-section-number">20.2</span> Uses of simulation</h2>
<p>The study of statistics started in the 1800s but only barely. The field’s modern version was almost entirely developed during the first half of the 20th century - notably a time when data and processing power were in short supply. Today, that’s not so much the case and if you did the assigned reading then you saw that statisticians are very much still grappling with how to teach statistics in light of the developments in computational power over the past 40 years.</p>
<p>Traditionally, statisticians are very concerned with assessing the normality of a sample, because the conclusions you get from traditional statistical methods depend on a sample coming from a normal distribution. Nowadays, there are a lot of clever methods that can avoid the need to assume normality. I’m going to show you some of those methods, because they help avoid getting into mathematical statistics. If you want to know more, one of the assigned readings was the introduction to a book that would be a great reference for self-guided study.</p>
<p>We will use simulation-based methods extensively today.</p>
<p>This is the density curve of a standard normal distribution:</p>
<div class="sourceCode" id="cb722"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb722-1"><a href="statistics.html#cb722-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set z to -4, 4</span></span>
<span id="cb722-2"><a href="statistics.html#cb722-2" aria-hidden="true" tabindex="-1"></a>z <span class="ot">=</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="at">length.out =</span> <span class="dv">1000</span>)</span>
<span id="cb722-3"><a href="statistics.html#cb722-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb722-4"><a href="statistics.html#cb722-4" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the standard normal density function with some annotations</span></span>
<span id="cb722-5"><a href="statistics.html#cb722-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>( <span class="at">x=</span>z, <span class="at">y=</span><span class="fu">dnorm</span>(z), <span class="at">bty=</span><span class="st">&#39;n&#39;</span>, <span class="at">type=</span><span class="st">&#39;l&#39;</span>, <span class="at">main=</span><span class="st">&quot;standard normal density&quot;</span>)</span>
<span id="cb722-6"><a href="statistics.html#cb722-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb722-7"><a href="statistics.html#cb722-7" aria-hidden="true" tabindex="-1"></a><span class="co"># annotate the density function with the 5% probability mass tails</span></span>
<span id="cb722-8"><a href="statistics.html#cb722-8" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="at">x=</span><span class="fu">c</span>(z[z<span class="sc">&lt;=</span><span class="fu">qnorm</span>(<span class="fl">0.025</span>)], <span class="fu">qnorm</span>(<span class="fl">0.025</span>), <span class="fu">min</span>(z)), <span class="at">y=</span><span class="fu">c</span>(<span class="fu">dnorm</span>(z[z<span class="sc">&lt;=</span><span class="fu">qnorm</span>(<span class="fl">0.025</span>)]), <span class="dv">0</span>, <span class="dv">0</span>), <span class="at">col=</span><span class="fu">grey</span>(<span class="fl">0.8</span>))</span>
<span id="cb722-9"><a href="statistics.html#cb722-9" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="at">x=</span><span class="fu">c</span>(z[z<span class="sc">&gt;=</span><span class="fu">qnorm</span>(<span class="fl">0.975</span>)], <span class="fu">max</span>(z), <span class="fu">qnorm</span>(<span class="fl">0.975</span>)), <span class="at">y=</span><span class="fu">c</span>(<span class="fu">dnorm</span>(z[z<span class="sc">&gt;=</span><span class="fu">qnorm</span>(<span class="fl">0.975</span>)]), <span class="dv">0</span>, <span class="dv">0</span>), <span class="at">col=</span><span class="fu">grey</span>(<span class="fl">0.8</span>))</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/annotated-density-tails-1.png" width="672" /></p>
<p>And this is a histogram of samples taken from that same distribution:</p>
<div class="sourceCode" id="cb723"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb723-1"><a href="statistics.html#cb723-1" aria-hidden="true" tabindex="-1"></a><span class="co"># sample 20 numbers from a standard normal and draw the histogram</span></span>
<span id="cb723-2"><a href="statistics.html#cb723-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="dv">20</span>)</span>
<span id="cb723-3"><a href="statistics.html#cb723-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>( <span class="fu">sort</span>(x), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##  [1] -2.64 -2.49 -1.19 -1.00 -0.97 -0.89 -0.73 -0.32 -0.23 -0.11  0.17  0.53
## [13]  0.56  0.62  0.65  0.68  0.91  1.35  1.67  1.77</code></pre>
<div class="sourceCode" id="cb725"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb725-1"><a href="statistics.html#cb725-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(x)</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/normal-histogram-1.png" width="672" /></p>
<p>Do the numbers seem to come from the high-density part of the Normal density curve? Are there any that don’t? It isn’t surprising if some of your <code>x</code> samples are not particularly close to zero. One out of twenty (that’s five percent) samples from a standard Normal population are greater than two or less than negative two, on average. That’s “on average” over the population. Your sample may be different.</p>
<p>Here is the density of the exponential distribution:</p>
<div class="sourceCode" id="cb726"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb726-1"><a href="statistics.html#cb726-1" aria-hidden="true" tabindex="-1"></a><span class="co"># draw the desity of an Exponential distribution</span></span>
<span id="cb726-2"><a href="statistics.html#cb726-2" aria-hidden="true" tabindex="-1"></a>t <span class="ot">=</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">5</span>, <span class="at">length.out=</span><span class="dv">1000</span>)</span>
<span id="cb726-3"><a href="statistics.html#cb726-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>( <span class="at">x=</span>t, <span class="at">y=</span><span class="fu">dexp</span>(t), <span class="at">bty=</span><span class="st">&#39;n&#39;</span>, <span class="at">type=</span><span class="st">&#39;l&#39;</span>)</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/exponential-density-1.png" width="672" /></p>
<p>And here is a histogram of 20 samples taken from that distribution:</p>
<div class="sourceCode" id="cb727"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb727-1"><a href="statistics.html#cb727-1" aria-hidden="true" tabindex="-1"></a><span class="co"># sample 20 numbers from a histogram and plot the histogram</span></span>
<span id="cb727-2"><a href="statistics.html#cb727-2" aria-hidden="true" tabindex="-1"></a>ex <span class="ot">=</span> <span class="fu">rexp</span>( <span class="dv">20</span> )</span>
<span id="cb727-3"><a href="statistics.html#cb727-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>( <span class="fu">sort</span>(ex), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##  [1] 0.00 0.24 0.42 0.51 0.63 0.66 0.75 0.82 0.83 0.92 0.95 0.99 1.23 1.29 1.40
## [16] 1.45 1.68 2.73 2.76 2.82</code></pre>
<div class="sourceCode" id="cb729"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb729-1"><a href="statistics.html#cb729-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>( ex )</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/exponential-histogram-1.png" width="672" /></p>
<p>The histograms are clearly different, but it would be difficult to definitively name the distribution of the data by looking at a sample.</p>
</div>
<div id="mathematical-statistics" class="section level2" number="20.3">
<h2><span class="header-section-number">20.3</span> Mathematical statistics</h2>
<p>The mean has some special properties: you’ve seen how we can calculate the frequency of samples being within an interval based on known distributions. But we need to know the distribution. It turns out that the distribution of the sample mean approaches the Normal distribution as the sample size increases, for almost any independent data. That allows us to create intervals and reason about the distribution of real data, even though the data’s distribution is unknown.</p>
<div id="law-of-large-numbers" class="section level3" number="20.3.1">
<h3><span class="header-section-number">20.3.1</span> Law of large numbers</h3>
<p>The law of large numbers says that if the individual measurements are independent, then the mean of a sample tends toward the mean of the population as the sample size gets larger. This is what we’d expect, since we showed the rate at which the variance of the sample mean gets smaller is <span class="math inline">\(1/n\)</span>.</p>
<div class="sourceCode" id="cb730"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb730-1"><a href="statistics.html#cb730-1" aria-hidden="true" tabindex="-1"></a>nn <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">8</span>, <span class="dv">12</span>, <span class="dv">20</span>, <span class="dv">33</span>, <span class="dv">45</span>, <span class="dv">66</span>, <span class="dv">100</span>)</span>
<span id="cb730-2"><a href="statistics.html#cb730-2" aria-hidden="true" tabindex="-1"></a>means <span class="ot">=</span> <span class="fu">sapply</span>( nn, <span class="cf">function</span>(n) <span class="fu">mean</span>( <span class="fu">rnorm</span>(n) ) )</span>
<span id="cb730-3"><a href="statistics.html#cb730-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nn, means, <span class="at">bty=</span><span class="st">&#39;n&#39;</span>, <span class="at">ylab =</span> <span class="st">&quot;sample mean&quot;</span>)</span>
<span id="cb730-4"><a href="statistics.html#cb730-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>, <span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/lln-1.png" width="672" /></p>
</div>
<div id="central-limit-theorem" class="section level3" number="20.3.2">
<h3><span class="header-section-number">20.3.2</span> Central limit theorem</h3>
<p>The most important mathematical result in statistics, the Central Limit Theorem says that if you take (almost) any sample of random numbers and calculate its mean, the distribution of the mean tends toward a normal distribution. We illustrate the “tending toward” with an arrow and it indicates that the distribution of a sample mean is only <em>approximately</em> Normal. But if the original samples were from a Normal distribution then the sample mean has an <em>exactly</em> Normal distribution. From here, I’ll start writing the mean of a random variable <span class="math inline">\(X\)</span> as <span class="math inline">\(\bar{X}\)</span> and the mean of a sample <span class="math inline">\(x\)</span> as <span class="math inline">\(\bar{x}\)</span>.</p>
<p><span class="math display">\[ \bar{X} \rightarrow N(\mu, \frac{\sigma^2}{n}) \]</span>
And because of the identities we learned before, you can write this as
<span class="math display">\[\frac{\bar{X} - \mu}{\sigma/\sqrt{n}} \rightarrow N(0, 1) \]</span></p>
<p>This is significant because we can use the standard normal functions on the right, and the data on the left, to start answering questions like, “what is the 95% confidence interval for the population mean?”</p>
<div class="sourceCode" id="cb731"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb731-1"><a href="statistics.html#cb731-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate 20 samples from a uniform distribution and plot their histogram</span></span>
<span id="cb731-2"><a href="statistics.html#cb731-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">=</span> <span class="dv">20</span></span>
<span id="cb731-3"><a href="statistics.html#cb731-3" aria-hidden="true" tabindex="-1"></a>u <span class="ot">=</span> <span class="fu">rexp</span>( N )</span>
<span id="cb731-4"><a href="statistics.html#cb731-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>( u )</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/clt-1.png" width="672" /></p>
<div class="sourceCode" id="cb732"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb732-1"><a href="statistics.html#cb732-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate 100 repeated samples of the same size, calculate the mean of each one, and plot the histogram of the means.</span></span>
<span id="cb732-2"><a href="statistics.html#cb732-2" aria-hidden="true" tabindex="-1"></a>B <span class="ot">=</span> <span class="dv">100</span></span>
<span id="cb732-3"><a href="statistics.html#cb732-3" aria-hidden="true" tabindex="-1"></a>uu <span class="ot">=</span> <span class="fu">numeric</span>( B )</span>
<span id="cb732-4"><a href="statistics.html#cb732-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>B ) {</span>
<span id="cb732-5"><a href="statistics.html#cb732-5" aria-hidden="true" tabindex="-1"></a>  uu[[i]] <span class="ot">=</span> <span class="fu">mean</span>( <span class="fu">rexp</span>(N) )</span>
<span id="cb732-6"><a href="statistics.html#cb732-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb732-7"><a href="statistics.html#cb732-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb732-8"><a href="statistics.html#cb732-8" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(uu)</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/clt-2.png" width="672" /></p>
<div class="sourceCode" id="cb733"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb733-1"><a href="statistics.html#cb733-1" aria-hidden="true" tabindex="-1"></a><span class="co"># what happens as B and N get larger and smaller? Do they play different roles?</span></span></code></pre></div>
</div>
</div>
<div id="statistical-inference" class="section level2" number="20.4">
<h2><span class="header-section-number">20.4</span> Statistical inference</h2>
<div id="confidence-intervals" class="section level3" number="20.4.1">
<h3><span class="header-section-number">20.4.1</span> Confidence intervals</h3>
<p>In the <code>fosdata</code> package there is a dataset called <code>mice_pot</code>, which contains data from an experiment where mice were dosed with THC and then measured for motor activity as a percentage of their baseline activity. We are going to look at the group that got a medium dose of THC.</p>
<div class="sourceCode" id="cb734"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb734-1"><a href="statistics.html#cb734-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extract just the mice that got the medium dose of THC</span></span>
<span id="cb734-2"><a href="statistics.html#cb734-2" aria-hidden="true" tabindex="-1"></a>mice_med <span class="ot">=</span> mice_pot[ mice_pot<span class="sc">$</span>group <span class="sc">==</span> <span class="dv">1</span>, ]</span>
<span id="cb734-3"><a href="statistics.html#cb734-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb734-4"><a href="statistics.html#cb734-4" aria-hidden="true" tabindex="-1"></a><span class="co"># assess normality with histogram and QQ plot</span></span>
<span id="cb734-5"><a href="statistics.html#cb734-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>( mice_med<span class="sc">$</span>percent_of_act )</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/mice-normality-1.png" width="672" /></p>
<div class="sourceCode" id="cb735"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb735-1"><a href="statistics.html#cb735-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>( mice_med<span class="sc">$</span>percent_of_act )</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/mice-normality-2.png" width="672" /></p>
<div id="find-the-80-confidence-interval-for-the-population-mean" class="section level4" number="20.4.1.1">
<h4><span class="header-section-number">20.4.1.1</span> Find the 80% confidence interval for the population mean</h4>
<p>Now we are using our sample to make some determination about the population, so this is statistical inference. Our best guess of the population mean is the sample mean, <code>mean( mice_med$percent_of_act )</code>, which is 99.1%. But to get a confidence interval, we need to use the formula
<span class="math display">\[ \bar{x} \pm t_{n-1, 0.1} * S / \sqrt{n} \]</span>
Fortunately, R can do all the work for us:</p>
<div class="sourceCode" id="cb736"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb736-1"><a href="statistics.html#cb736-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 80% confidence interval for location of mice_med mean:</span></span>
<span id="cb736-2"><a href="statistics.html#cb736-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>( mice_med<span class="sc">$</span>percent_of_act, <span class="at">conf.level=</span><span class="fl">0.8</span> )</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  mice_med$percent_of_act
## t = 13.068, df = 11, p-value = 4.822e-08
## alternative hypothesis: true mean is not equal to 0
## 80 percent confidence interval:
##   88.71757 109.38712
## sample estimates:
## mean of x 
##  99.05235</code></pre>
</div>
</div>
<div id="two-population-test" class="section level3" number="20.4.2">
<h3><span class="header-section-number">20.4.2</span> Two-population test</h3>
<p>The test of <span class="math inline">\(\mu_0 = 100\)</span> is a one-population test because it seeks to compare a single population against a specified standard. On the other hand, you may wish to assess the null hypothesis that the movement of mice in the high-THC group is equal to the movement of mice in the medium-THC group. This is called a two-population test, since there are two populations to compare against each other. The null hypothesis is <span class="math inline">\(\mu_{0, med} = \mu_{0, high}\)</span>. Testing a two-population hypothesis requires first assessing normality and also checking whether the variances are equal. There are separate procedures when the variances are equal vs. unequal.</p>
<div class="sourceCode" id="cb738"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb738-1"><a href="statistics.html#cb738-1" aria-hidden="true" tabindex="-1"></a><span class="co">#extract the samples to be compared</span></span>
<span id="cb738-2"><a href="statistics.html#cb738-2" aria-hidden="true" tabindex="-1"></a>a <span class="ot">=</span> mice_pot<span class="sc">$</span>percent_of_act[ mice_pot<span class="sc">$</span>group <span class="sc">==</span> <span class="dv">1</span>]</span>
<span id="cb738-3"><a href="statistics.html#cb738-3" aria-hidden="true" tabindex="-1"></a>b <span class="ot">=</span> mice_pot<span class="sc">$</span>percent_of_act[ mice_pot<span class="sc">$</span>group <span class="sc">==</span> <span class="dv">3</span>]</span>
<span id="cb738-4"><a href="statistics.html#cb738-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb738-5"><a href="statistics.html#cb738-5" aria-hidden="true" tabindex="-1"></a><span class="co"># check for equal variances - these are close enough</span></span>
<span id="cb738-6"><a href="statistics.html#cb738-6" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(a)</span></code></pre></div>
<pre><code>## [1] 689.4729</code></pre>
<div class="sourceCode" id="cb740"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb740-1"><a href="statistics.html#cb740-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(b)</span></code></pre></div>
<pre><code>## [1] 429.4551</code></pre>
<div class="sourceCode" id="cb742"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb742-1"><a href="statistics.html#cb742-1" aria-hidden="true" tabindex="-1"></a><span class="co"># confirm equal variances with a boxplot</span></span>
<span id="cb742-2"><a href="statistics.html#cb742-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(a, b)</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/two-pop-t.test-1.png" width="672" /></p>
<div class="sourceCode" id="cb743"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb743-1"><a href="statistics.html#cb743-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check whether the high-THC mice movement is Normal</span></span>
<span id="cb743-2"><a href="statistics.html#cb743-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (we already checked for the medium-dose mice)</span></span>
<span id="cb743-3"><a href="statistics.html#cb743-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(b)</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/two-pop-t.test-2.png" width="672" /></p>
<div class="sourceCode" id="cb744"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb744-1"><a href="statistics.html#cb744-1" aria-hidden="true" tabindex="-1"></a><span class="co"># two pop test</span></span>
<span id="cb744-2"><a href="statistics.html#cb744-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(a, b, <span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  a and b
## t = 2.7707, df = 20, p-value = 0.0118
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   7.014608 49.754345
## sample estimates:
## mean of x mean of y 
##  99.05235  70.66787</code></pre>
</div>
<div id="hypothesis-tests-for-non-normal-data" class="section level3" number="20.4.3">
<h3><span class="header-section-number">20.4.3</span> Hypothesis tests for non-normal data</h3>
<p>Just as with the confidence intervals, there is a bootstrap hypothesis test that can be used where the data are not normal. There are other options, too, with clever derivations. The one I’ll show you is the Wilcoxon test, which is based on the ranks of the data.</p>
<p>Since we’e already seen that the barnacles per square meter data are not normal, I will illustrate testing the null hypothesis that <span class="math inline">\(\mu_0\)</span> = 300 barnacles per square meter. This is a one-population test, and a two-sided alternative.</p>
<div class="sourceCode" id="cb746"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb746-1"><a href="statistics.html#cb746-1" aria-hidden="true" tabindex="-1"></a><span class="co"># wilcoxon test for 300 barnacles per square meter</span></span>
<span id="cb746-2"><a href="statistics.html#cb746-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>( barnacles<span class="sc">$</span>per_m )</span></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  barnacles$per_m
## V = 3916, p-value = 3.797e-16
## alternative hypothesis: true location is not equal to 0</code></pre>
</div>
</div>
<div id="regression" class="section level2" number="20.5">
<h2><span class="header-section-number">20.5</span> Regression</h2>
<p>Regression is a mathematical tool that allows you to estimate how some response variable is related to some predictor variable(s). There are methods that handle continuous or discrete responses of many different distributions, but we are going to focus on linear regression here.</p>
<p>Linear regression means that the relationship between the predictor variable(s) and the response is a linear one. To illustrate, we’ll create a plot of the relationship between the waist measurement and bmi of 81 adults:</p>
<div class="sourceCode" id="cb748"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb748-1"><a href="statistics.html#cb748-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the relationship between the waist_cm and bmi variables</span></span>
<span id="cb748-2"><a href="statistics.html#cb748-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(adipose, <span class="fu">plot</span>(waist_cm, bmi), <span class="at">bty=</span><span class="st">&#39;n&#39;</span> )</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/regression-example-1.png" width="672" /></p>
<p>The relationship between the two is apparently linear (you can imagine drawing a straight line through the data). The general mathematical form of a linear regression line is</p>
<p><span class="math display">\[ y = a + \beta x + \epsilon \]</span></p>
<p>Here, the response variable (e.g., BMI) is called <span class="math inline">\(y\)</span> and the predictor (e.g. waist measurement) is <span class="math inline">\(x\)</span>. The coefficient <span class="math inline">\(\beta\)</span> indicates how much the response changes for a change in the predictors (e.g., the expected change in BMI with a 1cm change in waist measurement). Variable <span class="math inline">\(a\)</span> denotes the intercept, which is a constant offset that aligns the mean of <span class="math inline">\(y\)</span> with the mean of <span class="math inline">\(x\)</span>. Finally, <span class="math inline">\(\epsilon\)</span> is the so-called residual error in the relationship. It represents the variation in the response that is not due to the predictor(s).</p>
<div id="fitting-a-regression-line" class="section level3" number="20.5.1">
<h3><span class="header-section-number">20.5.1</span> Fitting a regression line</h3>
<p>The R function to fit the model is called <code>lm()</code>. Let’s take a look at an example:</p>
<div class="sourceCode" id="cb749"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb749-1"><a href="statistics.html#cb749-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit the linear regression BMI vs waist_cm</span></span>
<span id="cb749-2"><a href="statistics.html#cb749-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">=</span> <span class="fu">lm</span>( bmi <span class="sc">~</span> waist_cm, <span class="at">data=</span>adipose )</span>
<span id="cb749-3"><a href="statistics.html#cb749-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb749-4"><a href="statistics.html#cb749-4" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the fitted regression: begin with the raw data</span></span>
<span id="cb749-5"><a href="statistics.html#cb749-5" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>( adipose, <span class="fu">plot</span>(waist_cm, bmi, <span class="at">bty=</span><span class="st">&#39;n&#39;</span>) )</span>
<span id="cb749-6"><a href="statistics.html#cb749-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb749-7"><a href="statistics.html#cb749-7" aria-hidden="true" tabindex="-1"></a><span class="co">#now plot the fitted regression line (in red)</span></span>
<span id="cb749-8"><a href="statistics.html#cb749-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>( <span class="fu">coef</span>(fit)[[<span class="dv">1</span>]], <span class="fu">coef</span>(fit)[[<span class="dv">2</span>]], <span class="at">col=</span><span class="st">&#39;red&#39;</span> )</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/bmi-vs-waist-regression-1.png" width="672" /></p>
</div>
<div id="assumptions-and-diagnostics" class="section level3" number="20.5.2">
<h3><span class="header-section-number">20.5.2</span> Assumptions and diagnostics</h3>
<p>“Fitting” a linear regression model involves estimating <span class="math inline">\(a\)</span> and <span class="math inline">\(\beta\)</span> in the regression equation. You can can do this fitting procedure using any data, but the results won’t be reliable unless some conditions are met. The conditions are:</p>
<ol style="list-style-type: decimal">
<li>Observations are independent.</li>
<li>The linear model is correct.</li>
<li>The residual error is Normally distributed.</li>
<li>The variance of the residual error is constant for all observations.</li>
</ol>
<p>The first of these conditions can’t be checked - it has to do with the design of the experiment. The rest can be checked, though, and I’ll take them in order.</p>
<div id="checking-that-the-linear-model-is-correct" class="section level4" number="20.5.2.1">
<h4><span class="header-section-number">20.5.2.1</span> Checking that the linear model is correct</h4>
<p>In the cast of a simple linear regression model (one predictor variable), you can check this by plotting the predictor against the response and looking for a linear trend. If you have more than one predictor variable, then you need to plot the predictions against the response to look for a linear trend. We’ll see an example by adding height as a predictor for BMI (in addition to waist measurement).</p>
<div class="sourceCode" id="cb750"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb750-1"><a href="statistics.html#cb750-1" aria-hidden="true" tabindex="-1"></a><span class="co"># linear model for BMI using waist size and height as predictors</span></span>
<span id="cb750-2"><a href="statistics.html#cb750-2" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">=</span> <span class="fu">lm</span>( bmi <span class="sc">~</span> waist_cm <span class="sc">+</span> stature_cm, <span class="at">data=</span>adipose )</span>
<span id="cb750-3"><a href="statistics.html#cb750-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb750-4"><a href="statistics.html#cb750-4" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the fitted versus the predicted values</span></span>
<span id="cb750-5"><a href="statistics.html#cb750-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>( fit2<span class="sc">$</span>fitted.values, adipose<span class="sc">$</span>bmi, <span class="at">bty=</span><span class="st">&#39;n&#39;</span> )</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/bmi-waist-height-1.png" width="672" /></p>
</div>
<div id="checking-that-the-residuals-are-normally-distributed" class="section level4" number="20.5.2.2">
<h4><span class="header-section-number">20.5.2.2</span> Checking that the residuals are normally distributed</h4>
<p>We have already learned about the QQ plot, which shows visually whether some values are Normally distributed. In order to depend upon the fit from a linear regression model, we need to see that the residuals are Normally distributed, and we use the QQ plot to check.</p>
</div>
<div id="checking-that-the-vaiance-is-constant" class="section level4" number="20.5.2.3">
<h4><span class="header-section-number">20.5.2.3</span> Checking that the vaiance is constant</h4>
<p>In an earlier part, we saw that the variance is the average of the squared error. But that would just be a single number, when we want to see if there is a trend. So like the QQ plot, you’l plot the residuals and use your eyeball to discern whether there is a trend in the residuals or if they are approximately constant - this is called the scale-location plot. The QQ plot and scale-location plot are both created by plotting the fitted model object</p>
<div class="sourceCode" id="cb751"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb751-1"><a href="statistics.html#cb751-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set up the pattern of the panels</span></span>
<span id="cb751-2"><a href="statistics.html#cb751-2" aria-hidden="true" tabindex="-1"></a><span class="fu">layout</span>( <span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">2</span>) )</span>
<span id="cb751-3"><a href="statistics.html#cb751-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb751-4"><a href="statistics.html#cb751-4" aria-hidden="true" tabindex="-1"></a><span class="co"># make the diagnostic plots</span></span>
<span id="cb751-5"><a href="statistics.html#cb751-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>( fit )</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/diagnostics-1.png" width="672" /></p>
<p>The “Residuals vs. Fitted” plot is checking whether the linear model is correct. There should be no obvious pattern if the data are linear (as is the casre here). The Scale-Location plot will have no obvios pattern if the variance of the residuals is constant, as is the case here (you might see a slight pattern in the smoothed red line but it isn’t obvious). And the QQ plot will look like a straight line if the residuals are from a Normal distribution, as is the case here. So this model is good. The fourth diagnostic plot is the Residuals vs. Leverage plot, which is used to identify influential outliers. We won’t get into that here.</p>
</div>
</div>
<div id="functions-for-inspecting-regression-fits" class="section level3" number="20.5.3">
<h3><span class="header-section-number">20.5.3</span> Functions for inspecting regression fits</h3>
<p>When you fit a linear regression model, you are estimating the parameters of the regression equation. In order to see those estimates, use the <code>summary()</code> function on the fitted model object.</p>
<div class="sourceCode" id="cb752"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb752-1"><a href="statistics.html#cb752-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get the model summary</span></span>
<span id="cb752-2"><a href="statistics.html#cb752-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>( fit2 )</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = bmi ~ waist_cm + stature_cm, data = adipose)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.1290 -1.0484 -0.2603  1.2661  5.2572 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 14.38196    3.82700   3.758 0.000329 ***
## waist_cm     0.29928    0.01461  20.491  &lt; 2e-16 ***
## stature_cm  -0.08140    0.02300  -3.539 0.000680 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.724 on 78 degrees of freedom
## Multiple R-squared:  0.844,  Adjusted R-squared:   0.84 
## F-statistic:   211 on 2 and 78 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Here you can see that the average marginal effect of one additional centimeter of waist measurement is to increase BMI by 0.3 and an additional centimeter of height is associated with a change to BMI of -0.08. You can get the coefficients from the fitted model object using the <code>coef()</code> function, and there are some other functions that allow you to generate the values shown in the summary table.</p>
<div class="sourceCode" id="cb754"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb754-1"><a href="statistics.html#cb754-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get the coefficients of the fitted regression</span></span>
<span id="cb754-2"><a href="statistics.html#cb754-2" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">=</span> <span class="fu">coef</span>( fit2 )</span>
<span id="cb754-3"><a href="statistics.html#cb754-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>( beta, <span class="dv">2</span> )</span></code></pre></div>
<pre><code>## (Intercept)    waist_cm  stature_cm 
##       14.38        0.30       -0.08</code></pre>
<p>Get the variance-covariance matrix:</p>
<div class="sourceCode" id="cb756"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb756-1"><a href="statistics.html#cb756-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>( <span class="fu">vcov</span>( fit2 ), <span class="dv">4</span>)</span></code></pre></div>
<div class="sourceCode" id="cb757"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb757-1"><a href="statistics.html#cb757-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compare the square root of the diagonals of the variance-covariance matrix</span></span>
<span id="cb757-2"><a href="statistics.html#cb757-2" aria-hidden="true" tabindex="-1"></a><span class="co"># to the standard errors are reported in the summary table:</span></span>
<span id="cb757-3"><a href="statistics.html#cb757-3" aria-hidden="true" tabindex="-1"></a>se <span class="ot">=</span> <span class="fu">sqrt</span>( <span class="fu">diag</span>( <span class="fu">vcov</span>(fit2) ))</span>
<span id="cb757-4"><a href="statistics.html#cb757-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb757-5"><a href="statistics.html#cb757-5" aria-hidden="true" tabindex="-1"></a><span class="co"># here are the standard errors:</span></span>
<span id="cb757-6"><a href="statistics.html#cb757-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>( se, <span class="dv">3</span> )</span></code></pre></div>
<pre><code>## (Intercept)    waist_cm  stature_cm 
##       3.827       0.015       0.023</code></pre>
<div class="sourceCode" id="cb759"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb759-1"><a href="statistics.html#cb759-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the t-statistics for the regression coefficients</span></span>
<span id="cb759-2"><a href="statistics.html#cb759-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (compare these to the t-statistics reorted in the summary table)</span></span>
<span id="cb759-3"><a href="statistics.html#cb759-3" aria-hidden="true" tabindex="-1"></a>t_stats <span class="ot">=</span> beta <span class="sc">/</span> se</span>
<span id="cb759-4"><a href="statistics.html#cb759-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb759-5"><a href="statistics.html#cb759-5" aria-hidden="true" tabindex="-1"></a><span class="co"># show the t-statistics:</span></span>
<span id="cb759-6"><a href="statistics.html#cb759-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>( t_stats, <span class="dv">2</span> )</span></code></pre></div>
<pre><code>## (Intercept)    waist_cm  stature_cm 
##        3.76       20.49       -3.54</code></pre>
<div class="sourceCode" id="cb761"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb761-1"><a href="statistics.html#cb761-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the p-values:</span></span>
<span id="cb761-2"><a href="statistics.html#cb761-2" aria-hidden="true" tabindex="-1"></a>pval <span class="ot">=</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>( <span class="fu">abs</span>(t_stats), <span class="at">df=</span><span class="dv">78</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span> )</span>
<span id="cb761-3"><a href="statistics.html#cb761-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(pval, <span class="dv">4</span>)</span></code></pre></div>
<pre><code>## (Intercept)    waist_cm  stature_cm 
##       3e-04       0e+00       7e-04</code></pre>
<div class="sourceCode" id="cb763"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb763-1"><a href="statistics.html#cb763-1" aria-hidden="true" tabindex="-1"></a><span class="co"># this is the residual standard error:</span></span>
<span id="cb763-2"><a href="statistics.html#cb763-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>( fit2<span class="sc">$</span>residuals ) <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">80</span> <span class="sc">/</span> <span class="dv">78</span>)</span></code></pre></div>
<pre><code>## [1] 1.72357</code></pre>
<div class="sourceCode" id="cb765"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb765-1"><a href="statistics.html#cb765-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R-squared is the proportion of variance</span></span>
<span id="cb765-2"><a href="statistics.html#cb765-2" aria-hidden="true" tabindex="-1"></a><span class="co"># explained by the regression model</span></span>
<span id="cb765-3"><a href="statistics.html#cb765-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>( <span class="dv">1</span> <span class="sc">-</span> <span class="fu">var</span>(fit2<span class="sc">$</span>residuals) <span class="sc">/</span> <span class="fu">var</span>(adipose<span class="sc">$</span>bmi), <span class="dv">3</span> )</span></code></pre></div>
<pre><code>## [1] 0.844</code></pre>
</div>
<div id="a-model-that-fails-diagnostics" class="section level3" number="20.5.4">
<h3><span class="header-section-number">20.5.4</span> A model that fails diagnostics</h3>
<p>We’ve seen a model that has good diagnostics. Now let’s look at one that doesn’t. This time, we’ll use linear regression to make a model of the relationship between waist measurement and the visceral adipose tissue fat (measured in grams). The visceral adipose tissue fat is abbreviated <code>vat</code> in the data. First, since the model uses a single predictor variable, let’s look at the relationship with a pair plot.</p>
<div class="sourceCode" id="cb767"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb767-1"><a href="statistics.html#cb767-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the relationship between waist_cm and vat</span></span>
<span id="cb767-2"><a href="statistics.html#cb767-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>( adipose, <span class="fu">plot</span>( waist_cm, vat, <span class="at">bty=</span><span class="st">&#39;n&#39;</span> ))</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/vat-plot-1.png" width="672" /></p>
<p>The plot is obviously not showing a linear relationship, which will violate one of the conditions for linear regression. Also, you can see that there is less variance of vat among the observations that have smaller waist measurements. So that will violate the assumption that the residual variance has no relationship to the fitted values. To see how these will show up in the diagnostic plots, we need to fit the linear regression model.</p>
<div class="sourceCode" id="cb768"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb768-1"><a href="statistics.html#cb768-1" aria-hidden="true" tabindex="-1"></a><span class="co"># estimate the model for vat</span></span>
<span id="cb768-2"><a href="statistics.html#cb768-2" aria-hidden="true" tabindex="-1"></a>fit_vat <span class="ot">=</span> <span class="fu">lm</span>( vat <span class="sc">~</span> waist_cm, <span class="at">data =</span> adipose )</span>
<span id="cb768-3"><a href="statistics.html#cb768-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb768-4"><a href="statistics.html#cb768-4" aria-hidden="true" tabindex="-1"></a><span class="co"># there is no problem creating the summary table:</span></span>
<span id="cb768-5"><a href="statistics.html#cb768-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>( fit_vat )</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = vat ~ waist_cm, data = adipose)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -996.25 -265.96  -61.87  191.24 1903.46 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -3604.196    334.241  -10.78   &lt;2e-16 ***
## waist_cm       51.353      3.937   13.04   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 479 on 79 degrees of freedom
## Multiple R-squared:  0.6829, Adjusted R-squared:  0.6789 
## F-statistic: 170.2 on 1 and 79 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb770"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb770-1"><a href="statistics.html#cb770-1" aria-hidden="true" tabindex="-1"></a><span class="co"># show the diagnostic plots</span></span>
<span id="cb770-2"><a href="statistics.html#cb770-2" aria-hidden="true" tabindex="-1"></a><span class="fu">layout</span>( <span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">2</span>) )</span>
<span id="cb770-3"><a href="statistics.html#cb770-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>( fit_vat )</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/vat-regression-diagnostics-1.png" width="672" /></p>
<p>There is obviously a curved pattern in the Residuals vs. Fitted plot, and in the Scale vs. Location plot. Residuals vs. Fitted shows a fan-shaped pattern, too, which reflects the increasing variance among the greater fitted values. The QQ plot is not a straight line, although the difference is not as obvious. In particular, the upper tail of residuals is heavier than expected. Together, all of these are indications that we may need to do a log transformation of the response. A log transformation helps to exaggerate the differences between smaller numbers (make the lower tail heavier) and collapse some difference among larger numbers (make the upper tail less heavy).</p>
<div class="sourceCode" id="cb771"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb771-1"><a href="statistics.html#cb771-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit a regression model where the response is log-transformed</span></span>
<span id="cb771-2"><a href="statistics.html#cb771-2" aria-hidden="true" tabindex="-1"></a>fit_log <span class="ot">=</span> <span class="fu">lm</span>( <span class="fu">log</span>(vat) <span class="sc">~</span> waist_cm, <span class="at">data=</span>adipose )</span>
<span id="cb771-3"><a href="statistics.html#cb771-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb771-4"><a href="statistics.html#cb771-4" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the diagnostics for the log-transformed model</span></span>
<span id="cb771-5"><a href="statistics.html#cb771-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>( fit_log )</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/log-vat-1.png" width="672" /><img src="17_basic-stats_files/figure-html/log-vat-2.png" width="672" /><img src="17_basic-stats_files/figure-html/log-vat-3.png" width="672" /><img src="17_basic-stats_files/figure-html/log-vat-4.png" width="672" /></p>
<p>The diagnostics do not look good after the log transformation, but now the problem is the opposite: a too-heavy lower tail and residual variance decreases as the fitted value increases. Perhaps a better transformation is something in between the raw data and the log transform. Try a square-root transformation.</p>
<div class="sourceCode" id="cb772"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb772-1"><a href="statistics.html#cb772-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit a model where the vat is square root transformed</span></span>
<span id="cb772-2"><a href="statistics.html#cb772-2" aria-hidden="true" tabindex="-1"></a>fit_sqrt <span class="ot">=</span> <span class="fu">lm</span>( <span class="fu">sqrt</span>(vat) <span class="sc">~</span> waist_cm, <span class="at">data=</span>adipose )</span>
<span id="cb772-3"><a href="statistics.html#cb772-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb772-4"><a href="statistics.html#cb772-4" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the diagnostics for the log-transformed model</span></span>
<span id="cb772-5"><a href="statistics.html#cb772-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>( fit_sqrt )</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/vat-sqrt-1.png" width="672" /><img src="17_basic-stats_files/figure-html/vat-sqrt-2.png" width="672" /><img src="17_basic-stats_files/figure-html/vat-sqrt-3.png" width="672" /><img src="17_basic-stats_files/figure-html/vat-sqrt-4.png" width="672" /></p>
<p>These look acceptable for real-world data.</p>
</div>
<div id="predictions-and-variability" class="section level3" number="20.5.5">
<h3><span class="header-section-number">20.5.5</span> Predictions and variability</h3>
<p>There are two scales of uncertainty for a regression model: uncertainty in the fitted relationship, and the uncertainty of a predicted outcome. The uncertainty of a prediction is always greater because it is calculated by adding the uncertainty of the fitted line to the uncertainty of a single data point around that fitted line. We can illustrate using the example of the model we just created to relate the waist measurement to the square root of vat. For this block of code, we’ll need the <code>mvtnorm</code> library to be loaded.</p>
<div class="sourceCode" id="cb773"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb773-1"><a href="statistics.html#cb773-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import mvtnorm. install it if necessary.</span></span>
<span id="cb773-2"><a href="statistics.html#cb773-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>( mvtnorm )</span>
<span id="cb773-3"><a href="statistics.html#cb773-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb773-4"><a href="statistics.html#cb773-4" aria-hidden="true" tabindex="-1"></a><span class="co"># draw the data on the transformed scale</span></span>
<span id="cb773-5"><a href="statistics.html#cb773-5" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>( adipose, <span class="fu">plot</span>(waist_cm, <span class="fu">sqrt</span>(vat), <span class="at">bty=</span><span class="st">&#39;n&#39;</span>) )</span>
<span id="cb773-6"><a href="statistics.html#cb773-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb773-7"><a href="statistics.html#cb773-7" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the fitted regression line</span></span>
<span id="cb773-8"><a href="statistics.html#cb773-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>( <span class="fu">coef</span>(fit_sqrt)[[<span class="dv">1</span>]], <span class="fu">coef</span>(fit_sqrt)[[<span class="dv">2</span>]], <span class="at">col=</span><span class="st">&#39;red&#39;</span> )</span>
<span id="cb773-9"><a href="statistics.html#cb773-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb773-10"><a href="statistics.html#cb773-10" aria-hidden="true" tabindex="-1"></a><span class="co"># plot 100 samples from the distributon of the regression line.</span></span>
<span id="cb773-11"><a href="statistics.html#cb773-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>) {</span>
<span id="cb773-12"><a href="statistics.html#cb773-12" aria-hidden="true" tabindex="-1"></a>  cc <span class="ot">=</span> <span class="fu">rmvnorm</span>( <span class="at">n=</span><span class="dv">1</span>, <span class="at">mean=</span><span class="fu">coef</span>(fit_sqrt), <span class="at">sigma=</span><span class="fu">vcov</span>(fit_sqrt) )</span>
<span id="cb773-13"><a href="statistics.html#cb773-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>( cc[[<span class="dv">1</span>]], cc[[<span class="dv">2</span>]], <span class="at">col=</span><span class="fu">grey</span>(<span class="fl">0.8</span>))</span>
<span id="cb773-14"><a href="statistics.html#cb773-14" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/predictions-1.png" width="672" /></p>
<p>Clearly, the variability of the data points is greater than the variability of the fitted line (that’s why they lie outside the envelope of the fitted lines). We can extract a confidence interval for fitted values or predictions with the <code>predict()</code> function.</p>
<div class="sourceCode" id="cb774"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb774-1"><a href="statistics.html#cb774-1" aria-hidden="true" tabindex="-1"></a><span class="co"># draw the data on the transformed scale</span></span>
<span id="cb774-2"><a href="statistics.html#cb774-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>( adipose, <span class="fu">plot</span>(waist_cm, <span class="fu">sqrt</span>(vat), <span class="at">bty=</span><span class="st">&#39;n&#39;</span>) )</span>
<span id="cb774-3"><a href="statistics.html#cb774-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb774-4"><a href="statistics.html#cb774-4" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the fitted regression line</span></span>
<span id="cb774-5"><a href="statistics.html#cb774-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>( <span class="fu">coef</span>(fit_sqrt)[[<span class="dv">1</span>]], <span class="fu">coef</span>(fit_sqrt)[[<span class="dv">2</span>]], <span class="at">col=</span><span class="st">&#39;red&#39;</span> )</span>
<span id="cb774-6"><a href="statistics.html#cb774-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb774-7"><a href="statistics.html#cb774-7" aria-hidden="true" tabindex="-1"></a><span class="co"># define some waist measurements where we&#39;ll construct confidence intervals</span></span>
<span id="cb774-8"><a href="statistics.html#cb774-8" aria-hidden="true" tabindex="-1"></a>pred_pts <span class="ot">=</span> <span class="fu">data.frame</span>( <span class="at">waist_cm =</span> <span class="fu">c</span>(<span class="dv">70</span>, <span class="dv">85</span>, <span class="dv">110</span>) )</span>
<span id="cb774-9"><a href="statistics.html#cb774-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb774-10"><a href="statistics.html#cb774-10" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the 90% CI at each of the pred_pts</span></span>
<span id="cb774-11"><a href="statistics.html#cb774-11" aria-hidden="true" tabindex="-1"></a>ff <span class="ot">=</span> <span class="fu">predict</span>(fit_sqrt, pred_pts, <span class="at">interval=</span><span class="st">&quot;confidence&quot;</span>, <span class="at">level=</span><span class="fl">0.9</span>)</span>
<span id="cb774-12"><a href="statistics.html#cb774-12" aria-hidden="true" tabindex="-1"></a>pp <span class="ot">=</span> <span class="fu">predict</span>(fit_sqrt, pred_pts, <span class="at">interval=</span><span class="st">&quot;prediction&quot;</span>, <span class="at">level=</span><span class="fl">0.9</span>)</span>
<span id="cb774-13"><a href="statistics.html#cb774-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb774-14"><a href="statistics.html#cb774-14" aria-hidden="true" tabindex="-1"></a><span class="co"># convert the confidence intervals to data.frames</span></span>
<span id="cb774-15"><a href="statistics.html#cb774-15" aria-hidden="true" tabindex="-1"></a>ff <span class="ot">=</span> <span class="fu">as.data.frame</span>(ff)</span>
<span id="cb774-16"><a href="statistics.html#cb774-16" aria-hidden="true" tabindex="-1"></a>pp <span class="ot">=</span> <span class="fu">as.data.frame</span>(pp)</span>
<span id="cb774-17"><a href="statistics.html#cb774-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb774-18"><a href="statistics.html#cb774-18" aria-hidden="true" tabindex="-1"></a><span class="co"># add the three confidence intervals to the plots</span></span>
<span id="cb774-19"><a href="statistics.html#cb774-19" aria-hidden="true" tabindex="-1"></a><span class="co"># (offset them a bit for clarity in the plot)</span></span>
<span id="cb774-20"><a href="statistics.html#cb774-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>) {</span>
<span id="cb774-21"><a href="statistics.html#cb774-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lines</span>( <span class="at">x=</span><span class="fu">rep</span>( pred_pts<span class="sc">$</span>waist_cm[[i]] <span class="sc">-</span> <span class="fl">0.5</span>, <span class="dv">2</span>),</span>
<span id="cb774-22"><a href="statistics.html#cb774-22" aria-hidden="true" tabindex="-1"></a>        <span class="at">y=</span><span class="fu">c</span>( ff<span class="sc">$</span>lwr[[i]], ff<span class="sc">$</span>upr[[i]] ), <span class="at">col=</span><span class="st">&#39;blue&#39;</span>, <span class="at">lwd=</span><span class="dv">2</span> )</span>
<span id="cb774-23"><a href="statistics.html#cb774-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb774-24"><a href="statistics.html#cb774-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lines</span>( <span class="at">x=</span><span class="fu">rep</span>( pred_pts<span class="sc">$</span>waist_cm[[i]] <span class="sc">+</span> <span class="fl">0.5</span>, <span class="dv">2</span>),</span>
<span id="cb774-25"><a href="statistics.html#cb774-25" aria-hidden="true" tabindex="-1"></a>        <span class="at">y=</span><span class="fu">c</span>( pp<span class="sc">$</span>lwr[[i]], pp<span class="sc">$</span>upr[[i]] ), <span class="at">col=</span><span class="st">&#39;orange&#39;</span>, <span class="at">lwd=</span><span class="dv">2</span> )</span>
<span id="cb774-26"><a href="statistics.html#cb774-26" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb774-27"><a href="statistics.html#cb774-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb774-28"><a href="statistics.html#cb774-28" aria-hidden="true" tabindex="-1"></a><span class="co"># add a legend</span></span>
<span id="cb774-29"><a href="statistics.html#cb774-29" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="fu">c</span>(<span class="st">&quot;90% CI (fitted values)&quot;</span>, <span class="st">&quot;90% CI (predicted values)&quot;</span>),</span>
<span id="cb774-30"><a href="statistics.html#cb774-30" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">&quot;topleft&quot;</span>, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;orange&quot;</span>), <span class="at">bty=</span><span class="st">&#39;n&#39;</span>)</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/prediction-intervals-1.png" width="672" /></p>
<p>One thing to notice about the confidence intervals is that the interval is smallest (so the precision of the estimation is greatest) at the mean of the predictor variable. This is a general rule of fitting regression.</p>
</div>
</div>
<div id="model-selection" class="section level2" number="20.6">
<h2><span class="header-section-number">20.6</span> Model selection</h2>
<p>Choosing how to represent your data is a common task in statistics. The most common target is to choose the representation (or model) that does the best job of predicting new data. We set this target because if we have a representation that predicts the future, then we can say it must accurately represent the process that generates the data.</p>
</div>
<div id="cross-validation" class="section level2" number="20.7">
<h2><span class="header-section-number">20.7</span> Cross-validation</h2>
<p>Unfortunately, we rarely have information about the future, so there isn’t new data to predict. One way to do prediction with the available data is to break it into a training part and a testing part. You make represent the training part with a model, and then use it to predict the left-out testing part. If you then swap the to parts and repeat the process, you’ll have a prediction for every data point. This would be called two-fold cross valdation because the data was broken into two parts.</p>
<p>It’s more common to break the data into more than two parts - typically five or ten or one per data point. Then one part is taken as the testing part and all the others go into the training part. The result is five-fold or ten-fold, or leave-one-out cross validation.</p>
<p>Let’s use cross-validation to do model selection. The model this time is a representation of the number of births per day in 1978 in the United States.</p>
<div class="sourceCode" id="cb775"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb775-1"><a href="statistics.html#cb775-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the data</span></span>
<span id="cb775-2"><a href="statistics.html#cb775-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>( births <span class="sc">~</span> day_of_year, <span class="at">color =</span> <span class="sc">~</span>wknd, <span class="at">data=</span>Births78 )</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/cv-1.png" width="672" /></p>
<div class="sourceCode" id="cb776"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb776-1"><a href="statistics.html#cb776-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make models with two through ten knots in the spline for day_of_year</span></span>
<span id="cb776-2"><a href="statistics.html#cb776-2" aria-hidden="true" tabindex="-1"></a>bmod2 <span class="ot">=</span> <span class="fu">lm</span>( births <span class="sc">~</span> wknd <span class="sc">+</span> <span class="fu">ns</span>(day_of_year, <span class="dv">2</span>), <span class="at">data=</span>Births78 )</span>
<span id="cb776-3"><a href="statistics.html#cb776-3" aria-hidden="true" tabindex="-1"></a>bmod4 <span class="ot">=</span> <span class="fu">lm</span>( births <span class="sc">~</span> wknd <span class="sc">+</span> <span class="fu">ns</span>(day_of_year, <span class="dv">4</span>), <span class="at">data=</span>Births78 )</span>
<span id="cb776-4"><a href="statistics.html#cb776-4" aria-hidden="true" tabindex="-1"></a>bmod6 <span class="ot">=</span> <span class="fu">lm</span>( births <span class="sc">~</span> wknd <span class="sc">+</span> <span class="fu">ns</span>(day_of_year, <span class="dv">6</span>), <span class="at">data=</span>Births78 )</span>
<span id="cb776-5"><a href="statistics.html#cb776-5" aria-hidden="true" tabindex="-1"></a>bmod8 <span class="ot">=</span> <span class="fu">lm</span>( births <span class="sc">~</span> wknd <span class="sc">+</span> <span class="fu">ns</span>(day_of_year, <span class="dv">8</span>), <span class="at">data=</span>Births78 )</span>
<span id="cb776-6"><a href="statistics.html#cb776-6" aria-hidden="true" tabindex="-1"></a>bmod10 <span class="ot">=</span> <span class="fu">lm</span>( births <span class="sc">~</span> wknd <span class="sc">+</span> <span class="fu">ns</span>(day_of_year, <span class="dv">10</span>), <span class="at">data=</span>Births78 )</span>
<span id="cb776-7"><a href="statistics.html#cb776-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb776-8"><a href="statistics.html#cb776-8" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the 2 and 10 knot models</span></span>
<span id="cb776-9"><a href="statistics.html#cb776-9" aria-hidden="true" tabindex="-1"></a><span class="fu">mod_plot</span>(bmod2, births<span class="sc">~</span>day_of_year <span class="sc">+</span> wknd) <span class="sc">+</span></span>
<span id="cb776-10"><a href="statistics.html#cb776-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>day_of_year, <span class="at">y=</span>births, <span class="at">color=</span>wknd), <span class="at">data=</span>Births78)</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/cv-2.png" width="672" /></p>
<div class="sourceCode" id="cb777"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb777-1"><a href="statistics.html#cb777-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mod_plot</span>(bmod10, births<span class="sc">~</span>day_of_year <span class="sc">+</span> wknd) <span class="sc">+</span></span>
<span id="cb777-2"><a href="statistics.html#cb777-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>day_of_year, <span class="at">y=</span>births, <span class="at">color=</span>wknd), <span class="at">data=</span>Births78)</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/cv-3.png" width="672" /></p>
<div class="sourceCode" id="cb778"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb778-1"><a href="statistics.html#cb778-1" aria-hidden="true" tabindex="-1"></a><span class="co"># cross-validate to choose the best model</span></span>
<span id="cb778-2"><a href="statistics.html#cb778-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mod_cv</span>( bmod2, bmod4, bmod6, bmod8, bmod10, <span class="at">k=</span><span class="fu">nrow</span>(Births78), <span class="at">ntrials=</span><span class="dv">1</span> )</span></code></pre></div>
<pre><code>## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA

## Warning in mean.default((actual - model_output)^2, na.rm = TRUE): argument is
## not numeric or logical: returning NA</code></pre>
<pre><code>##   mse  model
## 1  NA  bmod2
## 2  NA  bmod4
## 3  NA  bmod6
## 4  NA  bmod8
## 5  NA bmod10</code></pre>
<div class="sourceCode" id="cb781"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb781-1"><a href="statistics.html#cb781-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the data</span></span>
<span id="cb781-2"><a href="statistics.html#cb781-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mod_plot</span>(bmod6, births<span class="sc">~</span>day_of_year <span class="sc">+</span> wknd) <span class="sc">+</span></span>
<span id="cb781-3"><a href="statistics.html#cb781-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>day_of_year, <span class="at">y=</span>births, <span class="at">color=</span>wknd), <span class="at">data=</span>Births78)</span></code></pre></div>
<p><img src="17_basic-stats_files/figure-html/cv-4.png" width="672" /></p>
<p>Cross-validation suggests that six knots is the ideal number, because it has the smallest mean-squared error (mse). The resulting model looks good, too.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="network-analysis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="reshaping-tabular-data.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/ucdavisdatalab/adventures_in_data_science/edit/master/17_basic-stats.rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/ucdavisdatalab/adventures_in_data_science/blob/master/17_basic-stats.rmd",
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
